<br />
<div align="center" class="info_tablebox">
    <table class="hide" border="0" cellpadding="0" cellspacing="1">
                    <table class="width100" cellspacing="1">
                        <tbody>
                            <tr>
                                <td class="form-title">Documentation</td>
                                <td class="form-title">FAQ</td>
                                <td class="form-title" width="220">Contact Us</td>
                            </tr>
                            <tr class="row-2">
                                <td class="left">
                                        <?php if($this->documentation):?>
                                            <?php foreach($this->documentation as $documentation):?>
                                                <a href="/merchant/help-details/helpdesk_id/<?=$documentation['helpdesk_id']?>"><?=$documentation['h_subject']?></a><br />
                                            <?php endforeach;?>
                                        <?php endif;?>
                                </td>
                                <td class="left">
                                        <?php if($this->faq):?>
                                            <?php foreach($this->faq as $faq):?>
                                                <a href="/merchant/help-details/helpdesk_id/<?=$faq['helpdesk_id']?>"><?=$faq['h_subject']?></a><br />
                                            <?php endforeach;?>
                                        <?php endif;?>
                                </td>
                                <td class="left"><span class="small"><?=$this->ct?></span></td>
                            </tr>
                        </tbody>
                    </table>
    </table>
</div>