<br />
<div align="center"><H2>Order import preview</H2></div>
<?php if($this->notice):?>
<br />
<div align="center"><font color="red"><?=$this->notice?></font></div>
<?php else: ?>
<br />
<?php if($this->notice_paypal):?>
<strong>*<font color="green"><?=$this->notice_paypal?></font></strong>
<?php endif;?>
<div align="center">
    <form action="<?php if($this->ifpay){?>https://<?=$this->paypal_url?>/cgi-bin/webscr<?php }else{?>/merchant/import-order-confirm<?php };?>" method="POST" name='preview_form'>
        <table class="hide" border="0" cellpadding="0" cellspacing="1">
            <tbody>
                <tr>
                    <td valign="top" width="100%">
                        <table class="width100" cellspacing="1">
                            <tbody>
                                <tr>
                                    <td class="form-title">Merchant</td>
                                    <td class="form-title">First Name</td>
                                    <td class="form-title">Last Name</td>
                                    <td class="form-title">Supplier SKU</td>
                                    <td class="form-title">Merchant SKU</td>
                                    <td class="form-title">Qty</td>
                                    <td class="form-title">Amount</td>
                                    <td class="form-title">Balance</td>
                                    <td class="form-title">Credit</td>
                                    <td class="form-title">Result</td>
                                    <td class="form-title">Reason</td>
				</tr>
                                <?php if($this->list):
                                        $n = 1;
                                        foreach($this->list as $list_key => $list_val):
				?>
                                <tr class="row-<?php if(1==$n){echo $n;$n+=1;}else{echo $n;$n-=1;}?>">
                                    <td class="center"><?=$list_val[20]?></td>
                                    <td class="center"><?=$list_val[1]?></td>
                                    <td class="center"><?=$list_val[2]?></td>
                                    <td class="center"><?=$list_val[12]?></td>
                                    <td class="center"><?=$list_val[13]?></td>
                                    <td class="center"><?=$list_val[14]?></td>
                                    <td class="center"><?=number_format($list_val['order_amount'],2)?></td>
                                    <td class="center"><?=number_format($list_val['instant_balance'],2)?></td>
                                    
                                    <td class="center"><?=number_format($list_val['credit'],2)?></td>
                                    <?php if("Y" == $list_val['result']):?>
                                        <td class="center"><font color="green">Approved</font></td>
                                        <td class="center">&nbsp;</td>
                                    <?php else:?>
                                        <td class="center"><font color="red">Rejected</font></td>
                                        <td class="center"><?=$list_val['reason']?></td>
                                        <?php $is_rejected = 1;?>
                                    <?php endif;?>
                                </tr>
                                <input type="hidden" name="merchant_ref[<?=$list_key?>]" value="<?=$list_val[0]?>" />
                                <input type="hidden" name="shipping_first_name[<?=$list_key?>]" value="<?=$list_val[1]?>" />
                                <input type="hidden" name="shipping_last_name[<?=$list_key?>]" value="<?=$list_val[2]?>" />
                                <input type="hidden" name="shipping_company[<?=$list_key?>]" value="<?=$list_val[3]?>" />
                                <input type="hidden" name="merchant_company[<?=$list_key?>]" value="<?=$list_val[20]?>" />
                                <input type="hidden" name="user_id[<?=$list_key?>]" value="<?=$list_val['user_id']?>" />
                                <input type="hidden" name="shipping_address_1[<?=$list_key?>]" value="<?=$list_val[4]?>" />
                                <input type="hidden" name="shipping_address_2[<?=$list_key?>]" value="<?=$list_val[5]?>" />
                                <input type="hidden" name="shipping_suburb[<?=$list_key?>]" value="<?=$list_val[6]?>" />
                                <input type="hidden" name="shipping_state[<?=$list_key?>]" value="<?=$list_val[7]?>" />
                                <input type="hidden" name="shipping_postcode[<?=$list_key?>]" value="<?=$list_val[8]?>" />
                                <input type="hidden" name="shipping_country[<?=$list_key?>]" value="<?=$list_val[9]?>" />
                                <input type="hidden" name="shipping_phone[<?=$list_key?>]" value="<?=$list_val[10]?>" />
                                <input type="hidden" name="shipping_fax[<?=$list_key?>]" value="<?=$list_val[11]?>" />
                                <input type="hidden" name="supplier_sku[<?=$list_key?>]" value="<?=$list_val[12]?>" />
                                <input type="hidden" name="merchant_sku[<?=$list_key?>]" value="<?=$list_val[13]?>" />
                                <input type="hidden" name="quantity[<?=$list_key?>]" value="<?=$list_val[14]?>" />
                                <input type="hidden" name="shipping_method[<?=$list_key?>]" value="<?=$list_val[15]?>" />
                                <input type="hidden" name="shipping_instruction[<?=$list_key?>]" value="<?=$list_val[16]?>" />
                                <input type="hidden" name="tracking_number[<?=$list_key?>]" value="<?=$list_val[17]?>" />
                                <input type="hidden" name="serial_no[<?=$list_key?>]" value="<?=$list_val[18]?>" />
                                <input type="hidden" name="comments[<?=$list_key?>]" value="<?=$list_val[19]?>" />
                                <input type="hidden" name="pick_up[<?=$list_key?>]" value="<?=$list_val[21]?>" />
				<?php
                                      $pay_amount    =   abs($list_val['instant_balance'])-$list_val['credit'];
                                      endforeach;
                                    endif;
				?>
                                <input type="hidden" name="cmd" value="_xclick" />
                                
                                <input type="hidden" name="business" value="<?=$this->paypal_account?>" />
                                <input type="hidden" name="item_name" value="B2B Payment" />
                                <input type="hidden" name="item_number" value="B2B_Payment_<?=$this->userId?>"/>
                                <input type="hidden" name="amount" value="<?=$pay_amount?>" />
                                 <input type="hidden" name="userid" value="<?=$this->userId?>" />
                                 <input type="hidden" name="charset" value="utf-8"/>
                                <input type="hidden" name="bn" value="webasyst" />
                                <input type="hidden" name="return" value="<?=$this->paypal_return_url?>merchant/paypal-success/sessionid/<?=$this->sessionId?>" />
                                <input type="hidden" name="currency_code" value="AUD" />
                                
                                <tr>
                                    <td class="form-title" colspan="11">
                                        <?php if($this->ifpay):?>
                                        <input type="submit" value="Pay by Paypal"/>
                                        <?php else: ?>
                                        <input type="submit" value="Confirm Update" <?php if($is_rejected){echo "disabled='disabled'";}?> /> <?php if($is_rejected){echo "<font color='red'>* THE FORM CAN NOT BE SUBMITED DUE TO THE INVALID INFORMATION.</font>";}?></td>
                                        <?php endif;?>
                                </tr>
                                
                            </tbody>
                        </table>
                    </td>
                </tr>
            </tbody>
        </table>
    </form>
</div>
<?php endif;?>
