<br />
<div align="center"><H2>Order import preview</H2></div>
<?php if($this->notice):?>
<br />
<div align="center"><font color="red"><?=$this->notice?></font></div>
<?php else: ?>
<br />
<div align="center">
    <form action="/merchant/import-order-confirm" method="POST">
        <table class="hide" border="0" cellpadding="0" cellspacing="1">
            <tbody>
                <tr>
                    <td valign="top" width="100%">
                        <table class="width100" cellspacing="1">
                            <tbody>
                                <tr>
                                    <td class="form-title">First Name</td>
                                    <td class="form-title">Last Name</td>
                                    <td class="form-title">Address 1</td>
                                    <td class="form-title">Suburb</td>
                                    <td class="form-title">State</td>
                                    <td class="form-title">Postcode</td>
                                    <td class="form-title">Country</td>
                                    <td class="form-title">Supplier SKU</td>
                                    <td class="form-title">Qty</td>
                                    <td class="form-title">Result</td>
                                    <td class="form-title">Reason</td>
				</tr>
                                <?php if($this->list):
                                        $n = 1;
                                        foreach($this->list as $list_key => $list_val):
				?>
                                <tr class="row-<?php if(1==$n){echo $n;$n+=1;}else{echo $n;$n-=1;}?>">
                                    <td class="center"><?=$list_val[1]?></td>
                                    <td class="center"><?=$list_val[2]?></td>
                                    <td class="center"><?=$list_val[4]?></td>
                                    <td class="center"><?=$list_val[6]?></td>
                                    <td class="center"><?=$list_val[7]?></td>
                                    <td class="center"><?=$list_val[8]?></td>
                                    <td class="center"><?=$list_val[9]?></td>
                                    <td class="center"><?=$list_val[12]?></td>
                                    <td class="center"><?=$list_val[14]?></td>
                                    <?php if("Y" == $list_val['result']):?>
                                        <td class="center"><font color="green">Approved</font></td>
                                        <td class="center">&nbsp;</td>
                                    <?php else:?>
                                        <td class="center"><font color="red">Rejected</font></td>
                                        <td class="center"><?=$list_val['reason']?></td>
                                        <?php $is_rejected = 1;?>
                                    <?php endif;?>
                                </tr>
				<?php
                                            endforeach;
                                    endif;
				?>
                                <tr>
                                             *  Column A: $data[0] = Your Record #
         *  Column B: $data[1] = First Name
         *  Column C: $data[2] = Last Name
         *  Column D: $data[3] = Company
         *  Column E: $data[4] = Address 1
         *  Column F: $data[5] = Address 2
         *  Column G: $data[6] = Suburb
         *  Column H: $data[7] = State
         *  Column I: $data[8] = Postcode
         *  Column J: $data[9] = Country
         *  Column K: $data[10] = Phone
         *  Column L: $data[11] = Fax
         *  Column M: $data[12] = Supplier Item Code
         *  Column N: $data[13] = Topbuy SKU
         *  Column O: $data[14] = Qty
         *  Column P: $data[15] = Shipping Method
         *  Column Q: $data[16] = Shipping Instruction
         *  Column R: $data[17] = Tracking Number
         *  Column S: $data[18] = Serials No
         *  Column T: $data[19] = Comments 
                                    <td class="form-title" colspan="6">
                                        <input type="hidden" name="merchant_ref[<?=$list_key?>]" value="<?=$list_val[0]?>" />
                                        <input type="hidden" name="shipping_first_name[<?=$list_key?>]" value="<?=$list_val[1]?>" />
                                        <input type="hidden" name="shipping_last_name[<?=$list_key?>]" value="<?=$list_val[2]?>" />
                                        <input type="hidden" name="shipping_company[<?=$list_key?>]" value="<?=$list_val['user_id']?>" />
                                        <input type="hidden" name="shipping_address_1[<?=$list_key?>]" value="<?=$list_val[19]?>" />
                                        <input type="hidden" name="shipping_address_2[<?=$list_key?>]" value="<?=$list_val[19]?>" />
                                        <input type="hidden" name="shipping_suburb[<?=$list_key?>]" value="<?=$list_val[19]?>" />
                                        <input type="hidden" name="shipping_state[<?=$list_key?>]" value="<?=$list_val[19]?>" />
                                        <input type="hidden" name="shipping_post_code[<?=$list_key?>]" value="<?=$list_val[19]?>" />
                                        <input type="hidden" name="shipping_country[<?=$list_key?>]" value="<?=$list_val[19]?>" />
                                        <input type="hidden" name="shipping_phone[<?=$list_key?>]" value="<?=$list_val[19]?>" />
                                        <input type="hidden" name="shipping_fax[<?=$list_key?>]" value="<?=$list_val[19]?>" />
                                        <input type="hidden" name="supplier_sku[<?=$list_key?>]" value="<?=$list_val[19]?>" />
                                        <input type="hidden" name="merchant_sku[<?=$list_key?>]" value="<?=$list_val[19]?>" />
                                        <input type="hidden" name="quantity[<?=$list_key?>]" value="<?=$list_val[19]?>" />
                                        <input type="hidden" name="shipping_method[<?=$list_key?>]" value="<?=$list_val[19]?>" />
                                        <input type="hidden" name="shipping_instruction[<?=$list_key?>]" value="<?=$list_val[19]?>" />
                                        <input type="hidden" name="serial_no[<?=$list_key?>]" value="<?=$list_val[19]?>" />
                                        <input type="hidden" name="comments[<?=$list_key?>]" value="<?=$list_val[19]?>" />
                                        <input type="submit" value="Confirm Update" <?php if($is_rejected){echo "disabled='disabled'";}?> /> <?php if($is_rejected){echo "<font color='red'>* THE FORM CAN NOT BE SUBMITED DUE TO THE INVALID INFORMATION.</font>";}?></td>
                                </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
            </tbody>
        </table>
    </form>
</div>
<?php endif;?>