<script type="text/javascript">
$(function() 
{
    $('#start_date').datepicker(
    {
        numberOfMonths: 1,
        showButtonPanel: true,
        dateFormat: 'yy-mm-dd'
    });

    $('#end_date').datepicker(
    {
        numberOfMonths: 1,
        showButtonPanel: true,
        dateFormat: 'yy-mm-dd'
    });

	// BUGFIX: workaround for linux chrome browser
	// datepicker div is not hidden during load, this fix it
	if($('#ui-datepicker-div') && $('#ui-datepicker-div').css("display") != 'none')
	{
		$('#ui-datepicker-div').css("display", "none");
	}
});
</script>
<script language="javascript"><!--
function senfe(o,a,b,c,d){
 var t=document.getElementById(o).getElementsByTagName("tr");
 for(var i=0;i<t.length;i++){
  t[i].style.backgroundColor=(t[i].sectionRowIndex%2==0)?a:b;
  t[i].onclick=function(){
   if(this.x!="1"){
    this.x="1";//本来打算直接用背景色判断，FF获取到的背景是RGB值，不好判断
    this.style.backgroundColor=d;
   }else{
    this.x="0";
    this.style.backgroundColor=(this.sectionRowIndex%2==0)?a:b;
   }
  }
  t[i].onmouseover=function(){
   if(this.x!="1")this.style.backgroundColor=c;
  }
  t[i].onmouseout=function(){
   if(this.x!="1")this.style.backgroundColor=(this.sectionRowIndex%2==0)?a:b;
  }
 }
}
--></script>
<?php if($this->notice):?>
<strong>* <?php echo $this->notice;?></strong>
<?php endif;?>

<div class="info_tablebox">    
    <table class="hide" border="0" cellpadding="0" cellspacing="1">
        <div align="center" class="info_searchbox">
    <form action="/merchant/order-report" method="POST">
        From: <input type="text" class="input" name="start_date" id="start_date" size="10"  <?php if($this->start_date){echo "value= '".$this->start_date."'";} ?> />&nbsp;&nbsp;
        To: <input type="text" class="input"  name="end_date" id="end_date" size="10"  <?php if($this->end_date){echo "value= '".$this->end_date."'";} ?> />&nbsp;&nbsp;
        Merchant Ref: <input type="text" class="input"  name="merchant_ref" id="merchant_ref" size="10" <?php if($this->order_id){echo "value= '".$this->order_id."'";} ?> />&nbsp;&nbsp;
        Status: <select name="item_status" id="item_status">
                    <option value="-1">All</option>
                    <option value="0" <?php if(is_numeric($this->item_status) && $this->item_status == 0){?> selected="selected"<?php }?>>Pending</option>
                    <option value="1" <?php if(is_numeric($this->item_status) && $this->item_status == 1){?> selected="selected"<?php }?>>Approved</option>
                    <option value="3" <?php if(is_numeric($this->item_status) && $this->item_status == 3){?> selected="selected"<?php }?>>Processing</option>
                    <option value="4" <?php if(is_numeric($this->item_status) && $this->item_status == 4){?> selected="selected"<?php }?>>Sent</option>
                    <option value="5" <?php if(is_numeric($this->item_status) && $this->item_status == 5){?> selected="selected"<?php }?>>Canceled</option>
                    <option value="2" <?php if(is_numeric($this->item_status) && $this->item_status == 2){?> selected="selected"<?php }?>>Rejected</option>
                </select>&nbsp;&nbsp;
        <input type="submit" class="info_search_botton" value="Search" />
    </form>
</div>
        <table class="width100" cellspacing="1" id="senfe">
                        <tbody>
                            <tr>
                                <td class="form-title">Time</td>
                                <td class="form-title">Order ID</td>
                                <td class="form-title">Merchant Ref</td>
                                <td class="form-title">Supplier SKU</td>
                                <td class="form-title">Merchant SKU</td>
                                <td class="form-title">Order Amount<p style="margin:0">(Include GST and postage)</p></td>
                                <td class="form-title">Shipping Courier</td>
                                <td class="form-title">Tracking #</td>
                                <td class="form-title">Shipping Date</td>
                                <td class="form-title">Pick Up</td>
                                <td class="form-title">Status</td>
                                <td class="form-title">Action</td>
                            </tr>
                            <?php if($this->list):
                                    $n = 1;
                                    foreach($this->list as $key => $list):
                            ?>
                            <tr class="row-<?php if(1==$n){echo $n;$n+=1;}else{echo $n;$n-=1;}?>">
                                <td class="center"><span class="small"><?=date('H:i:s, d M Y ',strtotime($list['issue_time']))?></span></td>
                                <td class="center"><span class="small"><?=$list['main_db_order_id']?></span></td>
                                <td class="center"><span class="small"><?=$list['merchant_ref']?></span></td>
                                <td class="center"><span class="small"><?=$list['supplier_sku']?></span></td>
                                <td class="center"><span class="small"><?=$list['merchant_sku']?></span></td>
                                <td class="center"><span class="small"><?=$list['item_amount']?></span></td>
                                <td class="center"><span class="small"><?=$list['shipping_courier']?></span></td>
                                <td class="center"><span class="small"><?=$list['tracking_number']?></span></td>
                                <td class="center"><span class="small"><?=($list['shipping_date']!='0000-00-00 00:00:00')?$list['shipping_date']:''?></span></td>
                                <td class="center"><span class="small blue"><?=$list['pickup']?"<font color='red'>Yes</font>":"<font>No</font>"?></span></td>
                                <td class="center" onmouseover="show_status(<?php echo $key; ?>);" onmouseout="hide_status(<?php echo $key; ?>);"><span class="small">
                                        <?php 
                                        switch ($list['item_status'])
                                        {
                                            case 0:
                                                echo "<font color='red'>Pending</font>";
                                                break;
                                            case 1:
                                                echo "<font color='green'>Approved</font>";
                                                break;
                                            case 2:
                                                echo "<font color='red' style='TEXT-DECORATION: underline'>Rejected</font><div id='status_".$key."' class='api_response' style='display: none;'>".$list['api_response']."</div>";
                                                break;
                                            case 3:
                                                echo "<font color='green'>Processing</font>";
		                                break;
                                            case 4:
                                                echo "<font color='green'>Sent </font>";
		                                break;
                                            case 5:
                                                echo "<font color='red'>Cancelled</font>";
		                                break;
                                        }
                                        ?>
                                    </span></td>
                                    <td class="center"><span class="small"><a href="/merchant/order-view/order_id/<?=$list['purchase_order_id']?>">View</a></span></td>
                            </tr>
                            <?php
                                    endforeach;
                                endif;
                            ?>
                            <tr class="row-1">
                                <td colspan="12" style=" text-align: right;"><font color='red'>Total: $<?=$this->order_total?></font><br/><font color='green' style="font-size: 8pt;">(GST Included / Successful orders ONLY)</font></td>
                            </tr>
                        </tbody>
                    </table>
    </table>
</div>
<div style=" background:#999;  border:#FFF 1px;">
</div>
<div align="right"><?=$this->pagination?>&nbsp;&nbsp;</div>
<script language="javascript">
//senfe("表格名称","奇数行背景","偶数行背景","鼠标经过背景","点击后背景");
senfe("senfe","#f8f8f8","#e8f5f9","#ccc","");

function show_status(index)
{
	if($("#status_"+index))
	{
		$("#status_"+index).show();
	}
}

function hide_status(index)
{
	if($("#status_"+index))
	{
		$("#status_"+index).hide();
	}
}
</script>
