<script type="text/javascript">
$(function() 
{
    $('#start_date').datepicker(
    {
        numberOfMonths: 1,
        showButtonPanel: true,
        dateFormat: 'yy-mm-dd'
    });
});
$(function() 
{
    $('#end_date').datepicker(
    {
        numberOfMonths: 1,
        showButtonPanel: true,
        dateFormat: 'yy-mm-dd'
    });
});
</script>
<script language="javascript"><!--
function senfe(o,a,b,c,d){
 var t=document.getElementById(o).getElementsByTagName("tr");
 for(var i=0;i<t.length;i++){
  t[i].style.backgroundColor=(t[i].sectionRowIndex%2==0)?a:b;
  t[i].onclick=function(){
   if(this.x!="1"){
    this.x="1";//本来打算直接用背景色判断，FF获取到的背景是RGB值，不好判断
    this.style.backgroundColor=d;
   }else{
    this.x="0";
    this.style.backgroundColor=(this.sectionRowIndex%2==0)?a:b;
   }
  }
  t[i].onmouseover=function(){
   if(this.x!="1")this.style.backgroundColor=c;
  }
  t[i].onmouseout=function(){
   if(this.x!="1")this.style.backgroundColor=(this.sectionRowIndex%2==0)?a:b;
  }
 }
}
--></script>
<?php if($this->notice):?>
<strong>* <?php echo $this->notice;?></strong>
<?php endif;?>

<div class="info_tablebox">    
    <table class="hide" border="0" cellpadding="0" cellspacing="1">
        <div align="center" class="info_searchbox">
    <form action="/merchant/order-report" method="GET">
        From: <input type="text" class="input" name="start_date" id="start_date" size="10"  <?php if($this->start_date){echo "value= '".$this->start_date."'";} ?> />&nbsp;&nbsp;
        To: <input type="text" class="input"  name="end_date" id="end_date" size="10"  <?php if($this->end_date){echo "value= '".$this->end_date."'";} ?> />&nbsp;&nbsp;
        Merchant Ref: <input type="text" class="input"  name="merchant_ref" id="merchant_ref" size="10" <?php if($this->order_id){echo "value= '".$this->order_id."'";} ?> />&nbsp;&nbsp;
        <input type="submit" class="info_search_botton" value="Search" />
    </form>
</div>
        <table class="width100" cellspacing="1" id="senfe">
                        <tbody>
                            <tr>
                                <td class="form-title">Time</td>
                                <td class="form-title">Order ID</td>
                                <td class="form-title">Merchant Ref</td>
                                <td class="form-title">Supplier SKU</td>
                                <td class="form-title">Merchant SKU</td>
                                <td class="form-title">Order Amount</td>
                                <td class="form-title">Pick Up</td>
                                <td class="form-title">Status</td>
                            </tr>
                            <?php if($this->list):
                                    $n = 1;
                                    foreach($this->list as $list):
                            ?>
                            <tr class="row-<?php if(1==$n){echo $n;$n+=1;}else{echo $n;$n-=1;}?>">
                                <td class="center"><span class="small"><?=$list['issue_time']?></span></td>
                                <td class="center"><span class="small"><?=$list['main_db_order_id']?></span></td>
                                <td class="center"><span class="small"><?=$list['merchant_ref']?></span></td>
                                <td class="center"><span class="small"><?=$list['supplier_sku']?></span></td>
                                <td class="center"><span class="small"><?=$list['merchant_sku']?></span></td>
                                <td class="center"><span class="small"><?=$list['item_amount']?></span></td>
                                <td class="center"><span class="small blue"><?=$list['pickup']?"<font color='red'>Yes</font>":"<font>No</font>"?></span></td>
                                <td class="center"><span class="small">
                                        <?php 
                                        switch ($list['item_status'])
                                        {
                                            case 0:
                                                echo "<font color='red'>Pending</font>";
                                                break;
                                            case 1:
                                                echo "<font color='green'>Approved</font>";
                                                break;
                                            case 2:
                                                echo "<font color='red' style='TEXT-DECORATION: underline'>Rejected</font><div class='api_response'>".$list['api_response']."</div>";
                                                break;
                                        }
                                        ?>
                                    </span></td>
                            </tr>
                            <?php
                                    endforeach;
                                endif;
                            ?>
                        </tbody>
                    </table>
    </table>
</div>
<div style=" background:#999;  border:#FFF 1px;">
</div>
<div align="right"><?=$this->pagination?>&nbsp;&nbsp;</div>
<script language="javascript">
//senfe("表格名称","奇数行背景","偶数行背景","鼠标经过背景","点击后背景");
senfe("senfe","#f8f8f8","#e8f5f9","#ccc","");

</script>
<script language="javascript">
    $(".small font[color='red']").mouseover(function() {
        $(this).next().show();
    }).mouseout(function() {  
        $(this).next().hide();  
    });
</script>