<script type="text/javascript" src="/scripts/jquery.ui.core.js"></script>
<script type="text/javascript" src="/scripts/jquery.ui.dialog.js"></script>

<script language="JavaScript">
$(document).ready(function()
{
    $( "#dialog:ui-dialog" ).dialog( "destroy" );
    
	document.getElementById('dialog-modal').style.display="none";
 
    $('#add_item_href').click(function() 
	{
		$('input[name="id"]').val('');

		$('input[name="supplier_sku"]').val('');
		$('input[name="merchant_sku"]').val('');
		$('input[name="quantity"]').val('');
		$('input[name="merchant_ref"]').val('');
		$('input[name="shipping_method"]').val('');
		$('input[name="shipping_instruction"]').val('');
		$('input[name="comments"]').val('');

	    $('input[name="submit_form"]').val("Add");
		$( "#dialog-modal" ).dialog({
                    height: 400,
                    width: 550,
                    modal: true
		});
	});

	$(".pickup").click(function() 
	{
        if(this.checked==true)
        {
            document.getElementById('shipping_first_name').disabled='disabled';
            document.getElementById('shipping_last_name').disabled='disabled';
            document.getElementById('shipping_address_1').disabled='disabled';
            document.getElementById('shipping_address_2').disabled='disabled';
            document.getElementById('shipping_company').disabled='disabled';
            document.getElementById('shipping_suburb').disabled='disabled';
            document.getElementById('shipping_state').disabled='disabled';
            document.getElementById('shipping_postcode').disabled='disabled';
            document.getElementById('shipping_country').disabled='disabled';
            document.getElementById('shipping_phone').disabled='disabled';
        }
		else
		{
            document.getElementById('shipping_first_name').disabled=false;
            document.getElementById('shipping_last_name').disabled=false;
            document.getElementById('shipping_address_1').disabled=false;
            document.getElementById('shipping_address_2').disabled=false;
            document.getElementById('shipping_company').disabled=false;
            document.getElementById('shipping_suburb').disabled=false;
            document.getElementById('shipping_state').disabled=false;
            document.getElementById('shipping_postcode').disabled=false;
            document.getElementById('shipping_country').disabled=false;
            document.getElementById('shipping_phone').disabled=false;
        }
	
	});

    <?php if($_SESSION['place_order']['delivery']['pickup']):?>
    document.getElementById('shipping_first_name').disabled='disabled';
    document.getElementById('shipping_last_name').disabled='disabled';
    document.getElementById('shipping_address_1').disabled='disabled';
    document.getElementById('shipping_address_2').disabled='disabled';
    document.getElementById('shipping_company').disabled='disabled';
    document.getElementById('shipping_suburb').disabled='disabled';
    document.getElementById('shipping_state').disabled='disabled';
    document.getElementById('shipping_postcode').disabled='disabled';
    document.getElementById('shipping_country').disabled='disabled';
    document.getElementById('shipping_phone').disabled='disabled';
    <?php endif;?>
});

function edit_item(index)
{
	var session = [ <?php 

	if(is_array($_SESSION['place_order']['items']))
	{	
		$i = 0;

		foreach($_SESSION['place_order']['items'] as $key => $item)
		{
			echo (($i++ === 0) ? "" : ",\n")."{ 'id': '".$key."'";

			foreach($item as $obj_name => $obj_value)
			{
				echo ", '".$obj_name."': '".$obj_value."'";
			}
			echo " }";
		}
	}
?> ];

	if(index > -1 && index < session.length) // check
	{
		$('input[name="submit_form"]').val("Edit");

		for(var key in session[index])
		{
			if($('input[name="'+key+'"]')) // input exists
			{
				$('input[name="'+key+'"]').val(session[index][key]); // set value
			}
		}

		$( "#dialog-modal" ).dialog({
		            height: 400,
		            width: 550,
		            modal: true
		});
	}
}
</script>
<br />&nbsp;&nbsp;
<?php if($this->notice):?>
<strong>* <?php echo $this->notice;?></strong>
<?php endif;?>
<br />
<div align="center" class="info_tablebox">
    <form action="/merchant/place-order-preview" method="POST">
    <table class="hide" border="0" cellpadding="0" cellspacing="1">
                    <table class="width100" cellspacing="1">
                        <tbody>
                            <tr>
                                <td class="form-title" colspan="7" align="left">Items <a href="#" id="add_item_href"><img src="/styles/<?=$this->system_css?>/images/add.png" border="0" title="Add new item" alt="Add new item" /></a></td>
                            </tr>
                            <tr class="row-2">
                                <td class="center"><span class="small">Merchant Ref</span></td>
                                <td class="center"><span class="small">Supplier SKU</span></td>
                                <td class="center"><span class="small">Merchant SKU</span></td>
                                <td class="center"><span class="small">Qty.</span></td>
                                <td class="center" width="50"><span class="small">Action</span></td>
                            </tr>
                            <?php if($_SESSION['place_order']['items']):
                                    $n = 1;
                                    foreach($_SESSION['place_order']['items'] as $ikey => $items):
                            ?>
                            <tr class="row-<?php if(1==$n){echo $n;$n+=1;}else{echo $n;$n-=1;}?>">
                                <td class="center"><span class="small"><?=$items['merchant_ref']?></span></td>
                                <td class="center"><span class="small"><?=$items['supplier_sku']?></span></td>
                                <td class="center"><span class="small"><?=$items['merchant_sku']?></span></td>
                                <td class="center"><span class="small"><?=$items['quantity']?></span></td>
                                <td class="center"><span class="small"><a href="#" onclick="edit_item(<?php echo $ikey; ?>); return false;"><img src="/styles/<?=$this->system_css?>/images/edit.png" border="0" /></a>
<a href="/merchant/place-order-remove-item/id/<?=$ikey?>"><img src="/styles/<?=$this->system_css?>/images/del.png" border="0" /></a></span></td>
                            </tr>
                            <?php
                                    endforeach;
                                endif;
                            ?>
                        </tbody>
                    </table>
    </table>
    <table class="hide" border="0" cellpadding="0" cellspacing="1">
                    <table class="width100" cellspacing="1">
                        <tbody>
                            <tr>
                                <td class="form-title" colspan="4">Shipping Information ( Pick Up<input type="checkbox" name="pickup" id="pickup" class="pickup" <?php if($_SESSION['place_order']['delivery']['pickup']){echo "checked='checked'";}?> />)</td>
                            </tr>
                            <tr class="row-2">
                                <td class="right" width="200"><span class="small">First Name</span></td>
                                <td class="left"><span class="small"><input type="text" name="shipping_first_name" id="shipping_first_name" value="<?=$_SESSION['place_order']['delivery']['shipping_first_name']?>" /> <font color="red"> *</font></span></td>
                                <td class="right"><span class="small">Last Name</span></td>
                                <td class="left"><span class="small"><input type="text" name="shipping_last_name" id="shipping_last_name" value="<?=$_SESSION['place_order']['delivery']['shipping_last_name']?>" /> <font color="red"> *</font></span></td>
                            </tr>
                            <tr class="row-1">
                                <td class="right"><span class="small">Address 1</span></td>
                                <td class="left"><span class="small"><input type="text" name="shipping_address_1" id="shipping_address_1" value="<?=$_SESSION['place_order']['delivery']['shipping_address_1']?>" /> <font color="red"> *</font></span></td>
                                <td class="right"><span class="small">Address 2</span></td>
                                <td class="left"><span class="small"><input type="text" name="shipping_address_2" id="shipping_address_2" value="<?=$_SESSION['place_order']['delivery']['shipping_address_2']?>" /></span></td>
                            </tr>
                            <tr class="row-2">
                                <td class="right"><span class="small">Company</span></td>
                                <td class="left"><span class="small"><input type="text" name="shipping_company" id="shipping_company" value="<?=$_SESSION['place_order']['delivery']['shipping_company']?>" /> </span></td>
                                <td class="right"><span class="small">Suburb</span></td>
                                <td class="left"><span class="small"><input type="text" name="shipping_suburb" id="shipping_suburb" value="<?=$_SESSION['place_order']['delivery']['shipping_suburb']?>" /><font color="red"> *</font></span></td>
                            </tr>
                            <tr class="row-1">
                                <td class="right"><span class="small">State</span></td>
                                <td class="left"><span class="small"><input type="text" name="shipping_state" id="shipping_state" value="<?=$_SESSION['place_order']['delivery']['shipping_state']?>" /><font color="red"> *</font></span></td>
                                <td class="right"><span class="small">Postcode</span></td>
                                <td class="left"><span class="small"><input type="text" name="shipping_postcode" id="shipping_postcode" value="<?=$_SESSION['place_order']['delivery']['shipping_postcode']?>" /> <font color="red"> *</font></span></td>
                            </tr>
                            <tr class="row-2">
                                <td class="right"><span class="small">Country</span></td>
                                <td class="left"><span class="small">
                                        <select name="shipping_country" id="shipping_country">
                                            <?php foreach($this->countries as $ct_key => $ct_val):?>
                                            <option value="<?=$ct_val?>" <?php if($ct_key==$_SESSION['place_order']['delivery']['shipping_country']){echo "selected='selected'";}?>><?=$ct_val?></option>
                                            <?php endforeach;?>
                                        </select> <font color="red"> *</font>
                                    </span></td>
                                <td class="right"><span class="small">Phone</span></td>
                                <td class="left"><span class="small"><input type="text" name="shipping_phone" id="shipping_phone" value="<?=$_SESSION['place_order']['delivery']['shipping_phone']?>" /><font color="red"> *</font></span></td>
                            </tr>
                        </tbody>
                    </table>
    </table>
    <table class="hide" border="0" cellpadding="0" cellspacing="1">
        <tbody>
            <tr>
                <td valign="top" width="100%">
                    <table class="width100" cellspacing="1">
                        <tbody>
                            <tr>
                                <td class="info_Recharge"><input class="special_button_style_green" type="submit" value="Continue" /></td>
                            </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
        </tbody>
    </table>
    </form>
</div>

<div id="dialog-modal" title="Item form">
    <form action="/merchant/place-order-item-form" method="POST" id="item_form" name="item_form">
		<input type="hidden" name="id" />
        <table width="100%" border="0">
            <tr>
                <td>Supplier SKU:</td>
                <td><input type="text" name="supplier_sku" /> *</td>
            </tr>
            <tr>
                <td>Merchant SKU:</td>
                <td><input type="text" name="merchant_sku" /></td>
            </tr>
            <tr>
                <td>Quantity:</td>
                <td><input type="text" name="quantity" /> *</td>
            </tr>
            <tr>
                <td>Merchant Ref:</td>
                <td><input type="text" name="merchant_ref" /></td>
            </tr>
            <tr>
                <td>Shipping Method:</td>
                <td><input type="text" name="shipping_method" /></td>
            </tr>
            <tr>
                <td>Shipping Instruction:</td>
                <td><input type="text" name="shipping_instruction"  /></td>
            </tr>
            <tr>
                <td>Comments:</td>
                <td><input type="text" name="comments"  /></td>
            </tr>
            <tr>
                <td colspan="2"><input name="submit_form" type="submit" value="Apply" /></td>
            </tr>
        </table>
    </form>
</div>
