<br />
<div align="center"><H2>Place Order Preview</H2></div>
<?php if($this->notice):?>
<br />
<div align="center"><font color="red"><?=$this->notice?></font></div>
<?php else: ?>
<br />
<div align="center">
    <form action="/merchant/place-order-confirm" method="POST">
        <table class="hide" border="0" cellpadding="0" cellspacing="1">
            <tbody>
                <tr>
                    <td valign="top" width="100%">
                        <table class="width100" cellspacing="1">
                            <tbody>
                                <tr>
                                    <td class="form-title">Merchant</td>
                                    <td class="form-title">First Name</td>
                                    <td class="form-title">Last Name</td>
                                    <td class="form-title">Supplier SKU</td>
                                    <td class="form-title">Merchant SKU</td>
                                    <td class="form-title">Qty</td>
                                    <td class="form-title">Amount</td>
                                    <td class="form-title">Balance</td>
                                    <td class="form-title">Credit</td>
                                    <td class="form-title">Result</td>
                                    <td class="form-title">Reason</td>
				</tr>
                                <?php if($this->list):
                                        $n = 1;
                                        foreach($this->list as $list_key => $list_val):
				?>
                                <tr class="row-<?php if(1==$n){echo $n;$n+=1;}else{echo $n;$n-=1;}?>">
                                    <td class="center"><?=$list_val['merchant_company']?></td>
                                    <td class="center"><?=$list_val['shipping_first_name']?></td>
                                    <td class="center"><?=$list_val['shipping_last_name']?></td>
                                    <td class="center"><?=$list_val['supplier_sku']?></td>
                                    <td class="center"><?=$list_val['merchant_sku']?></td>
                                    <td class="center"><?=$list_val['quantity']?></td>
                                    <td class="center"><?=number_format($list_val['order_amount'],2)?></td>
                                    <td class="center"><?=number_format($list_val['instant_balance'],2)?></td>
                                    <td class="center"><?=number_format($list_val['credit'],2)?></td>
                                    <?php if("Y" == $list_val['result']):?>
                                        <td class="center"><font color="green">Approved</font></td>
                                        <td class="center">&nbsp;</td>
                                    <?php else:?>
                                        <td class="center"><font color="red">Rejected</font></td>
                                        <td class="center"><?=$list_val['reason']?></td>
                                        <?php $is_rejected = 1;?>
                                    <?php endif;?>
                                </tr>
                                <input type="hidden" name="merchant_ref[<?=$list_key?>]" value="<?=$list_val['merchant_ref']?>" />
                                <input type="hidden" name="shipping_first_name[<?=$list_key?>]" value="<?=$list_val['shipping_first_name']?>" />
                                <input type="hidden" name="shipping_last_name[<?=$list_key?>]" value="<?=$list_val['shipping_last_name']?>" />
                                <input type="hidden" name="shipping_company[<?=$list_key?>]" value="<?=$list_val['shipping_company']?>" />
                                <input type="hidden" name="merchant_company[<?=$list_key?>]" value="<?=$list_val['merchant_company']?>" />
                                <input type="hidden" name="user_id[<?=$list_key?>]" value="<?=$list_val['user_id']?>" />
                                <input type="hidden" name="shipping_address_1[<?=$list_key?>]" value="<?=$list_val['shipping_address_1']?>" />
                                <input type="hidden" name="shipping_address_2[<?=$list_key?>]" value="<?=$list_val['shipping_address_2']?>" />
                                <input type="hidden" name="shipping_suburb[<?=$list_key?>]" value="<?=$list_val['shipping_suburb']?>" />
                                <input type="hidden" name="shipping_state[<?=$list_key?>]" value="<?=$list_val['shipping_state']?>" />
                                <input type="hidden" name="shipping_postcode[<?=$list_key?>]" value="<?=$list_val['shipping_postcode']?>" />
                                <input type="hidden" name="shipping_country[<?=$list_key?>]" value="<?=$list_val['shipping_country']?>" />
                                <input type="hidden" name="shipping_phone[<?=$list_key?>]" value="<?=$list_val['shipping_phone']?>" />
                                <input type="hidden" name="shipping_fax[<?=$list_key?>]" value="<?=$list_val['shipping_fax']?>" />
                                <input type="hidden" name="supplier_sku[<?=$list_key?>]" value="<?=$list_val['supplier_sku']?>" />
                                <input type="hidden" name="merchant_sku[<?=$list_key?>]" value="<?=$list_val['merchant_sku']?>" />
                                <input type="hidden" name="quantity[<?=$list_key?>]" value="<?=$list_val['quantity']?>" />
                                <input type="hidden" name="shipping_method[<?=$list_key?>]" value="<?=$list_val['shipping_method']?>" />
                                <input type="hidden" name="shipping_instruction[<?=$list_key?>]" value="<?=$list_val['shipping_instruction']?>" />
                                <input type="hidden" name="tracking_number[<?=$list_key?>]" value="<?=$list_val['tracking_number']?>" />
                                <input type="hidden" name="serial_no[<?=$list_key?>]" value="<?=$list_val['serial_no']?>" />
                                <input type="hidden" name="comments[<?=$list_key?>]" value="<?=$list_val['comments']?>" />
                                <input type="hidden" name="pick_up[<?=$list_key?>]" value="<?=$list_val['pick_up']?>" />
				<?php
                                            endforeach;
                                    else:
                                        $is_rejected = 1; //no items
                                    endif;
				?>
                                <tr>
                                    <td class="form-title" colspan="10">
                                        <input type="submit" value="Confirm Update" <?php if($is_rejected){echo "disabled='disabled'";}?> /> <?php if($is_rejected){echo "<font color='red'>* THE FORM CAN NOT BE SUBMITED DUE TO THE INVALID INFORMATION.</font>";}?></td>
                                </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
            </tbody>
        </table>
    </form>
</div>
<?php endif;?>