
<div align="center" class="info_tablebox">
<div align="center"><H2>Place Order Preview</H2></div>
<?php if($this->notice):?>

<div align="center"><font color="red"><?=$this->notice?></font></div>
<?php else: ?>

    <form action="<?php if($this->ifpay){?>https://<?=$this->paypal_url?>/cgi-bin/webscr<?php }else{?>/merchant/place-order-confirm<?php };?>" method="POST" name='preview_form'>
        <table class="hide" border="0" cellpadding="0" cellspacing="1">
                        <table class="width100" cellspacing="1">
                            <tbody>
                                <tr>
                                    <td class="form-title">Merchant</td>
                                    <td class="form-title">First Name</td>
                                    <td class="form-title">Last Name</td>
                                    <td class="form-title">Product Name</td>
                                    <td class="form-title">Thumbnail</td>
                                    <td class="form-title">Supplier SKU</td>
                                    <td class="form-title">Merchant SKU</td>
                                    <td class="form-title">Qty</td>
                                    <td class="form-title">Amount</td>
                                    <td class="form-title">Balance</td>
                                    <td class="form-title">Credit</td>
                                    <td class="form-title">Result</td>
                                    <td class="form-title">Reason</td>
				</tr>
                                <?php if($this->list):
                                        $n = 1;
                                        foreach($this->list as $list_key => $list_val):
				?>
                                <tr class="row-<?php if(1==$n){echo $n;$n+=1;}else{echo $n;$n-=1;}?>">
                                    <td class="center"><?=$list_val['merchant_company']?></td>
                                    <td class="center"><?=$list_val['shipping_first_name']?></td>
                                    <td class="center"><?=$list_val['shipping_last_name']?></td>
                                    <td class="center"><?=$list_val['product_name']?></td>
                                    <td class="center"><?php ?></td>
                                    <td class="center"><?=$list_val['supplier_sku']?></td>
                                    <td class="center"><?=$list_val['merchant_sku']?></td>
                                    <td class="center"><?=$list_val['quantity']?></td>
                                    <td class="center"><?=number_format($list_val['order_amount'],2)?></td>
                                    <td class="center"><?=number_format($list_val['instant_balance'],2)?></td>
                                    <td class="center"><?=number_format($list_val['credit'],2)?></td>
                                    <?php if("Y" == $list_val['result']):?>
                                        <td class="center"><font color="green">Approved</font></td>
                                        <td class="center">&nbsp;</td>
                                    <?php else:?>
                                        <td class="center"><font color="red">Rejected</font></td>
                                        <td class="center"><?=$list_val['reason']?></td>
                                        <?php $is_rejected = 1;?>
                                    <?php endif;?>
                                </tr>
                                <input type="hidden" name="merchant_ref[<?=$list_key?>]" value="<?=$list_val['merchant_ref']?>" />
                                <input type="hidden" name="shipping_first_name[<?=$list_key?>]" value="<?=$list_val['shipping_first_name']?>" />
                                <input type="hidden" name="shipping_last_name[<?=$list_key?>]" value="<?=$list_val['shipping_last_name']?>" />
                                <input type="hidden" name="shipping_company[<?=$list_key?>]" value="<?=$list_val['shipping_company']?>" />
                                <input type="hidden" name="merchant_company[<?=$list_key?>]" value="<?=$list_val['merchant_company']?>" />
                                <input type="hidden" name="user_id[<?=$list_key?>]" value="<?=$list_val['user_id']?>" />
                                <input type="hidden" name="shipping_address_1[<?=$list_key?>]" value="<?=$list_val['shipping_address_1']?>" />
                                <input type="hidden" name="shipping_address_2[<?=$list_key?>]" value="<?=$list_val['shipping_address_2']?>" />
                                <input type="hidden" name="shipping_suburb[<?=$list_key?>]" value="<?=$list_val['shipping_suburb']?>" />
                                <input type="hidden" name="shipping_state[<?=$list_key?>]" value="<?=$list_val['shipping_state']?>" />
                                <input type="hidden" name="shipping_postcode[<?=$list_key?>]" value="<?=$list_val['shipping_postcode']?>" />
                                <input type="hidden" name="shipping_country[<?=$list_key?>]" value="<?=$list_val['shipping_country']?>" />
                                <input type="hidden" name="shipping_phone[<?=$list_key?>]" value="<?=$list_val['shipping_phone']?>" />
                                <input type="hidden" name="shipping_fax[<?=$list_key?>]" value="<?=$list_val['shipping_fax']?>" />
                                <input type="hidden" name="supplier_sku[<?=$list_key?>]" value="<?=$list_val['supplier_sku']?>" />
                                <input type="hidden" name="merchant_sku[<?=$list_key?>]" value="<?=$list_val['merchant_sku']?>" />
                                <input type="hidden" name="quantity[<?=$list_key?>]" value="<?=$list_val['quantity']?>" />
                                <input type="hidden" name="shipping_method[<?=$list_key?>]" value="<?=$list_val['shipping_method']?>" />
                                <input type="hidden" name="shipping_instruction[<?=$list_key?>]" value="<?=$list_val['shipping_instruction']?>" />
                                <input type="hidden" name="tracking_number[<?=$list_key?>]" value="<?=$list_val['tracking_number']?>" />
                                <input type="hidden" name="serial_no[<?=$list_key?>]" value="<?=$list_val['serial_no']?>" />
                                <input type="hidden" name="comments[<?=$list_key?>]" value="<?=$list_val['comments']?>" />
                                <input type="hidden" name="pick_up[<?=$list_key?>]" value="<?=$list_val['pick_up']?>" />
				<?php
                                             $pay_amount    =   abs($list_val['instant_balance'])-$list_val['credit'];
                                            endforeach;
                                    else:
                                        $is_rejected = 1; //no items
                                    endif;
				?>
                                <?php if($this->flat_paypal == 1):?>
                                    <input type="hidden" name="flat_paypal" value="1" />
                                <?php endif;?>
                                
                                <input type="hidden" name="cmd" value="_xclick" />
                                <input type="hidden" name="business" value="<?=$this->paypal_account?>" />
                                <input type="hidden" name="item_name" value="B2B Payment" />
                                <input type="hidden" name="item_number" value="b2b-payment-<?=$this->userId?>"/>
                                <input type="hidden" name="amount" value="<?=$pay_amount;?>" />
                                 <input type="hidden" name="userid" value="<?=$this->userId?>" />
                                <input type="hidden" name="bn" value="webasyst" />
                                <input type="hidden" name="return" value="<?=$this->paypal_return_url?>merchant/paypal-place-order/sessionid/<?=$this->sessionId?>" />
                                <input type="hidden" name="notify_url" value="<?=$this->paypal_return_url?>scheduled/paypal-notify/userid/<?=$this->userId?>"/>
                                <input type="hidden" name="currency_code" value="AUD" />
                                <tr>
                                    <td class="info_Recharge" colspan="12">
                                         <?php if($this->ifpay):?>
                                        <input type="submit" value="Pay by Paypal"/>
                                        <?php else: ?>
                                        <input type="submit" value="Confirm Update" <?php if($is_rejected){echo "disabled='disabled'";}?> /> <?php if($is_rejected){echo "<font color='red'>* THE FORM CAN NOT BE SUBMITED DUE TO THE INVALID INFORMATION.</font>";}?>
                                        <?php endif ?>
                                     </td>   
                                </tr>
                            </tbody>
                        </table>
        </table>
    </form>
    <script type="application/javascript">
		$("input[type=submit]").click(function(){
			$("input[type=submit]").attr('disabled','disabled');
		})			
	</script>
</div>
<?php endif;?>