<br />
<div align="center" class="info_tablebox">
    <table class="hide" border="0" cellpadding="0" cellspacing="1">
                    <table class="width100" cellspacing="1">
                        <tbody>
                            <tr>
                                <td class="info_Recharge" colspan="2">
                                    Recharge your account via BPAY
                                    <br />
                                    <img src="/images/bpay.gif" border="0" />
                                </td>
                            </tr>
                            <tr class="row-1">
                                <td class="right" width="50%"><H2>Biller Code: </H2></td>
                                <td class="left" width="50%"><H2><?=$this->biller_code?></H2></td>
                            </tr>
                            <tr class="row-2">
                                <td class="right" width="50%"><H2>Your Reference Number: </H2></td>
                                <td class="left" width="50%"><H2><?=$this->user['bpay_ref']?></H2></td>
                            </tr>
                        </tbody>
                    </table>
    </table>
</div>