<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
	<link rel="SHORTCUT ICON" href="/images/favicon.ico">
	<link rel="stylesheet" type="text/css" href="/styles/default.css">
	<meta http-equiv="Content-type" content="text/html; charset=UTF-8">
	<title><?=$this->title?> - <?=$this->system_title?></title>
</head>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
	<link rel="SHORTCUT ICON" href="/images/favicon.ico">
	<link rel="stylesheet" type="text/css" href="/styles/default.css">
	<meta http-equiv="Content-type" content="text/html; charset=UTF-8">
	<title><?=$this->title?> - <?=$this->system_title?></title>
</head>
<body>
<div class="login_topbg">
    <div class="login_logo"></div>
</div>
<!--<div align="center"><H1><?=$this->system_title?></H1></div>-->
<div class="login_main">
<form action="/login/index" method="POST" name="form1" id="form1"><input type="hidden" name="url" value="<?=$this->url?>" /> 
<div class="login_txt">
    <ul>
        <li class="font">Email:</li>
        <li><input class="login_input" name="email" type="text" id="email" /></li>
    </ul> 
    <ul>
        <li class="font">Password:</li>
        <li><input class="login_input" name="password" id="password" type="password" /></li>
    </ul>   
    <div style=" height: 45px;"><input class="login_button" type="submit" name="button" id="button" value="" /> <span  class="login_prompt" color="red"><?=$this->msg;?></span></div>
     
</div>
 </form>
<div class="login_footer"><?=$this->system_title?> <?=$this->system_version?>Copyright © <?=date("Y");?> CrazySales</div>
</div>



</body>
</html>
