<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
	<link rel="SHORTCUT ICON" href="/images/favicon.ico">
	<link rel="stylesheet" type="text/css" href="/styles/default.css">
	<meta http-equiv="Content-type" content="text/html; charset=UTF-8">
	<title><?=$this->title?> - <?=$this->system_title?></title>
</head>
<body>
<br /><br />
<div align="center"><H1><?=$this->system_title?></H1></div>
<br /><br />
<table class="width100 no-print" cellspacing="0">
	<tbody>
		<tr>
			<td class="menu">
                <font color="red"><?=$this->msg;?></font>
                <br /><br />
                <form action="/login/index" method="z" name="form1" id="form1"><input type="hidden" name="url" value="<?=$this->url?>" />
                    <table border="0" width="100%">
                        <tr>
                            <td>Email</td>
                            <td><input name="email" type="text" id="email" /></td>
                        </tr>
                        <tr>
                            <td>Password</td>
                            <td><input type="password" name="password" id="password" style="margin-top:5px;" /></td>
                        </tr>
                        <tr>
                            <td colspan="2"><input type="submit" name="button" id="button" value="Login" /></td>
                        </tr>
                    </table>
              </form>
            </td>
		</tr>
	</tbody>
</table>

<br>
<table width="100%" border="0" cellpadding="0" cellspacing="0">
	<tbody>
		<tr valign="top">
			<td><div align="right">
				<span class="timer"><?=$this->system_title?> <?=$this->system_version?><br />
				<address>Copyright © <?=date("Y");?> CrazySales</address>
				<span>
				</div>
			</td>
		</tr>
	</tbody>
</table>
</body>
</html>
