<script type="text/javascript">
$(function() 
{
    $('#start_date').datepicker(
    {
        numberOfMonths: 1,
        showButtonPanel: true,
        dateFormat: 'yy-mm-dd'
    });
});
$(function() 
{
    $('#end_date').datepicker(
    {
        numberOfMonths: 1,
        showButtonPanel: true,
        dateFormat: 'yy-mm-dd'
    });
});
</script>
<br />
<div align="center">
    <form action="/admin/admin-order-report/user_id/<?=$this->user_id?>" method="GET">
        From <input type="text" name="start_date" id="start_date" size="5"  <?php if($this->start_date){echo "value= '".$this->start_date."'";} ?> />&nbsp;&nbsp;
        To <input type="text" name="end_date" id="end_date" size="5"  <?php if($this->end_date){echo "value= '".$this->end_date."'";} ?> />&nbsp;&nbsp;
        Order ID <input type="text" name="order_id" id="order_id" size="5" <?php if($this->order_id){echo "value= '".$this->order_id."'";} ?> />&nbsp;&nbsp;
        <input type="submit" value="Search" />
    </form>
</div>
<br />
<div align="center">
    <table class="hide" border="0" cellpadding="0" cellspacing="1">
        <tbody>
            <tr>
                <td valign="top" width="100%">
                    <table class="width100" cellspacing="1">
                        <tbody>
                            <tr>
                                <td class="form-title">Time</td>
                                <td class="form-title">Order ID</td>
                                <td class="form-title">Order Status</td>
                                <td class="form-title">Item Title</td>
                                <td class="form-title">Order Amount</td>
                            </tr>
                            <?php if($this->list):
                                    $n = 1;
                                    foreach($this->list as $list):
                            ?>
                            <tr class="row-<?php if(1==$n){echo $n;$n+=1;}else{echo $n;$n-=1;}?>">
                                <td class="center"><span class="small"><?=$list['issue_time']?></span></td>
                                <td class="center"><span class="small"><?=$list['order_id']?></span></td>
                                <td class="center"><span class="small"><?=$list['order_status']?></span></td>
                                <td class="center"><span class="small"><?=$list['item_title']?></span></td>
                                <td class="center"><span class="small"><?=$list['order_amount']?></span></td>
                            </tr>
                            <?php
                                    endforeach;
                                endif;
                            ?>
                        </tbody>
                    </table>
                </td>
            </tr>
        </tbody>
    </table>
</div>
<div align="right"><?=$this->pagination?>&nbsp;&nbsp;</div>