<script type="text/javascript">
$(function() 
{
    $('#start_date').datepicker(
    {
        numberOfMonths: 1,
        showButtonPanel: true,
        dateFormat: 'yy-mm-dd'
    });

    $('#end_date').datepicker(
    {
        numberOfMonths: 1,
        showButtonPanel: true,
        dateFormat: 'yy-mm-dd'
    });

	// BUGFIX: workaround for linux chrome browser
	// datepicker div is not hidden during load, this fix it
	if($('#ui-datepicker-div') && $('#ui-datepicker-div').css("display") != 'none')
	{
		$('#ui-datepicker-div').css("display", "none");
	}
});
</script>
<br />
<div class="info_tablebox" >
<div align="center" class="info_searchbox" >
    <form action="/admin/admin-order-report/user_id/<?=$this->user_id?>" method="GET">
        From <input type="text"class="input" name="start_date" id="start_date" size="10"  <?php if($this->start_date){echo "value= '".$this->start_date."'";} ?> />&nbsp;&nbsp;
        To <input type="text" class="input" name="end_date" id="end_date" size="10"  <?php if($this->end_date){echo "value= '".$this->end_date."'";} ?> />&nbsp;&nbsp;
        Merchant Ref <input  class="input"type="text" name="merchant_ref" id="merchant_ref" size="10" <?php if($this->order_id){echo "value= '".$this->order_id."'";} ?> />&nbsp;&nbsp;
        <input type="submit" class="info_search_botton" value="Search" />
    </form>
</div>
<div align="center">
    <table class="hide" border="0" cellpadding="0" cellspacing="1">
                    <table class="width100" cellspacing="1">
                        <tbody>
                            <tr>
                                <td class="form-title">Time</td>
                                <td class="form-title">Order ID</td>
                                <td class="form-title">Merchant Ref</td>
                                <td class="form-title">Supplier SKU</td>
                                <td class="form-title">Merchant SKU</td>
                                <td class="form-title">Order Amount<p style="margin:0">(Include GST and postage)</p></td>
                                <td class="form-title">Status</td>
                                <td class="form-title">Action</td>
                            </tr>
                            <?php if($this->list):
                                    $n = 1;
                                    foreach($this->list as $key => $list):
                            ?>
                            <tr class="row-<?php if(1==$n){echo $n;$n+=1;}else{echo $n;$n-=1;}?>">
                                <td class="center"><span class="small"><?=date('H:i:s, d M Y ',strtotime($list['issue_time']))?></span></td>
                                <td class="center"><span class="small"><?=$list['main_db_order_id']?></span></td>
                                <td class="center"><span class="small"><?=$list['merchant_ref']?></span></td>
                                <td class="center"><span class="small"><?=$list['supplier_sku']?></span></td>
                                <td class="center"><span class="small"><?=$list['merchant_sku']?></span></td>
                                <td class="center"><span class="small"><?=$list['item_amount']?></span></td>
                                <td class="center" onmouseover="show_status(<?php echo $key; ?>);" onmouseout="hide_status(<?php echo $key; ?>);"><span class="small">
								<?php
                                    switch ($list['item_status'])
                                    {
                                        case 0:
                                            echo "<font color='red'>Pending</font>";
                                            break;
                                        case 1:
                                            echo "<font color='green'>Approved</font>";
                                            break;
                                        case 2:
                                            echo "<font color='red' style='TEXT-DECORATION: underline'>Rejected</font><div id='status_".$key."' class='api_response' style='display: none;'>".$list['api_response']."</div>";
                                            break;
                                    }
								?>      
                                    </span></td>
                                <td class="center"><span class="small"><a href="/admin/admin-order-view/user_id/<?=$this->user_id?>/order_id/<?=$list['purchase_order_id']?>">View</a></span></td>
                            </tr>
                            <?php
                                    endforeach;
                                endif;
                            ?>
                        </tbody>
                    </table>
</div>
<div align="right"><?=$this->pagination?>&nbsp;&nbsp;</div>
</div>
<script language="javascript">
function show_status(index)
{
	if($("#status_"+index))
	{
	 	$("#status_"+index).show();
	}
}

function hide_status(index)
{
	if($("#status_"+index))
	{
	 	$("#status_"+index).hide();
	}
}
</script>
