<br />
<div align="center"><H2>Admin Order import preview</H2></div>
<?php if($this->notice):?>
<br />
<div align="center"><font color="red"><?=$this->notice?></font></div>
<?php else: ?>
<br />
<div align="center">
    <form action="/admin/admin-import-order-confirm" method="POST">
        <table class="hide" border="0" cellpadding="0" cellspacing="1">
            <tbody>
                <tr>
                    <td valign="top" width="100%">
                        <table class="width100" cellspacing="1">
                            <tbody>
                                <tr>
                                    <td class="form-title">Merchant</td>
                                    <td class="form-title">First Name</td>
                                    <td class="form-title">Last Name</td>
                                    <td class="form-title">Product Name</td>
                                    <td class="form-title">Thumbnail</td>
                                    <td class="form-title">Supplier SKU</td>
                                    <td class="form-title">Merchant SKU</td>
                                    <td class="form-title">Qty</td>
                                    <td class="form-title">Amount</td>
                                    <td class="form-title">Balance</td>
                                    <td class="form-title">Credit</td>
                                    <td class="form-title">Result</td>
                                    <td class="form-title">Reason</td>
				</tr>
                                <?php if($this->list):
                                        $n = 1;
                                        foreach($this->list as $list_key => $list_val):
				?>
                                <tr class="row-<?php if(1==$n){echo $n;$n+=1;}else{echo $n;$n-=1;}?>">
                                    <td class="center"><?=$list_val[20]?></td>
                                    <td class="center"><?=$list_val[1]?></td>
                                    <td class="center"><?=$list_val[2]?></td>
                                    <td class="center"><?=$list_val['product_name']?></td>
                                    <td class="center"><image src="<?=$list_val['imageURL1'] ?>" height="50" /></td>
                                    <td class="center"><?=$list_val[12]?></td>
                                    <td class="center"><?=$list_val[13]?></td>
                                    <td class="center"><?=$list_val[14]?></td>
                                    <td class="center"><?=number_format($list_val['order_amount'],2)?></td>
                                    <td class="center"><?=number_format($list_val['instant_balance'],2)?></td>
                                    <td class="center"><?=number_format($list_val['credit'],2)?></td>
                                    <?php if("Y" == $list_val['result']):?>
                                        <td class="center"><font color="green">Approved</font></td>
                                        <td class="center">&nbsp;</td>
                                    <?php else:?>
                                        <td class="center"><font color="red">Rejected</font></td>
                                        <td class="center"><?=$list_val['reason']?></td>
                                        <?php $is_rejected = 1;?>
                                    <?php endif;?>
                                </tr>
                                <input type="hidden" name="merchant_ref[<?=$list_key?>]" value="<?=$list_val[0]?>" />
                                <input type="hidden" name="shipping_first_name[<?=$list_key?>]" value="<?=$list_val[1]?>" />
                                <input type="hidden" name="shipping_last_name[<?=$list_key?>]" value="<?=$list_val[2]?>" />
                                <input type="hidden" name="shipping_company[<?=$list_key?>]" value="<?=$list_val[3]?>" />
                                <input type="hidden" name="merchant_company[<?=$list_key?>]" value="<?=$list_val[20]?>" />
                                <input type="hidden" name="user_id[<?=$list_key?>]" value="<?=$list_val['user_id']?>" />
                                <input type="hidden" name="shipping_address_1[<?=$list_key?>]" value="<?=$list_val[4]?>" />
                                <input type="hidden" name="shipping_address_2[<?=$list_key?>]" value="<?=$list_val[5]?>" />
                                <input type="hidden" name="shipping_suburb[<?=$list_key?>]" value="<?=$list_val[6]?>" />
                                <input type="hidden" name="shipping_state[<?=$list_key?>]" value="<?=$list_val[7]?>" />
                                <input type="hidden" name="shipping_postcode[<?=$list_key?>]" value="<?=$list_val[8]?>" />
                                <input type="hidden" name="shipping_country[<?=$list_key?>]" value="<?=$list_val[9]?>" />
                                <input type="hidden" name="shipping_phone[<?=$list_key?>]" value="<?=$list_val[10]?>" />
                                <input type="hidden" name="shipping_fax[<?=$list_key?>]" value="<?=$list_val[11]?>" />
                                <input type="hidden" name="supplier_sku[<?=$list_key?>]" value="<?=$list_val[12]?>" />
                                <input type="hidden" name="merchant_sku[<?=$list_key?>]" value="<?=$list_val[13]?>" />
                                <input type="hidden" name="quantity[<?=$list_key?>]" value="<?=$list_val[14]?>" />
                                <input type="hidden" name="shipping_method[<?=$list_key?>]" value="<?=$list_val[15]?>" />
                                <input type="hidden" name="shipping_instruction[<?=$list_key?>]" value="<?=$list_val[16]?>" />
                                <input type="hidden" name="tracking_number[<?=$list_key?>]" value="<?=$list_val[17]?>" />
                                <input type="hidden" name="serial_no[<?=$list_key?>]" value="<?=$list_val[18]?>" />
                                <input type="hidden" name="comments[<?=$list_key?>]" value="<?=$list_val[19]?>" />
                                <input type="hidden" name="pick_up[<?=$list_key?>]" value="<?=$list_val[21]?>" />
				<?php
                                            endforeach;
                                    endif;
				?>
                                <tr>
                                    <td class="form-title" colspan="13">
                                        <input type="button" value="Confirm Update" <?php if($is_rejected){echo "disabled='disabled'";}?> /> <?php if($is_rejected){echo "<font color='red'>* THE FORM CAN NOT BE SUBMITED DUE TO THE INVALID INFORMATION.</font>";}?></td>
                                </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
            </tbody>
        </table>
    </form>
    <script type="application/javascript">
		$("input[type=button]").click(function(){
			$("input[type=button]").attr('disabled','disabled');
			$("form").submit();
		})		
	</script>
</div>
<?php endif;?>