<div class="info_tablebox" align="center">
<div align="center"><H2>Import the CSV file to recharge merchants' accounts</H2></div>
<div align="center"><?php if($this->notice):?><?=$this->notice?><?php endif;?></div>
<div align="center">
    <form action="/admin/bpay-import-preview" method="POST"  enctype="multipart/form-data">
        <table class="hide" border="0" cellpadding="0" cellspacing="1">
                        <table class="width100" cellspacing="1">
                            <tbody>
                                <tr class="row-1">
                                    <td class="right" width="50%"><input type="file" name="csvf" id="csvf" /></td>
                                    <td class="left" width="50%"><input class="info_botton" type="submit" value="Continue" /></td>
                                </tr>
                            </tbody>
                        </table>
        </table>
    </form>
</div>
</div>
<br />
<span class="red">&nbsp;* <a href="/samples/import_order_sample.csv" >Download a CSV sample</a></span>
