<br />
<div align="center"><H2>Import the CSV file to recharge merchants' accounts</H2></div>
<br />
<div align="center"><?php if($this->notice):?><font color="red"><?=$this->notice?></font><?php endif;?></div>
<br />
<div align="center">
    <form action="/admin/bpay-import-preview" method="POST"  enctype="multipart/form-data">
        <table class="hide" border="0" cellpadding="0" cellspacing="1">
            <tbody>
                <tr>
                    <td valign="top" width="100%">
                        <table class="width100" cellspacing="1">
                            <tbody>
                                <tr class="row-1">
                                    <td class="right" width="50%"><input type="file" name="csvf" id="csvf" /></td>
                                    <td class="left" width="50%"><input type="submit" value="Continue" /></td>
                                </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
            </tbody>
        </table>
    </form>
</div>