<script type="text/javascript">
$(function() 
{
    $('#start_date').datepicker(
    {
        numberOfMonths: 1,
        showButtonPanel: true,
        dateFormat: 'yy-mm-dd'
    });

    $('#end_date').datepicker(
    {
        numberOfMonths: 1,
        showButtonPanel: true,
        dateFormat: 'yy-mm-dd'
    });

	// BUGFIX: workaround for linux chrome browser
	// datepicker div is not hidden during load, this fix it
	if($('#ui-datepicker-div') && $('#ui-datepicker-div').css("display") != 'none')
	{
		$('#ui-datepicker-div').css("display", "none");
	}
});                                                        
</script>
<br />
<div class="info_tablebox" >
<div align="center" class="info_searchbox" >
    <form action="/admin/dd-product-list" method="POST">
        Product Code <input  class="input"type="text" name="product_code" id="product_code" size="10" <?php if($this->product_code){echo "value= '".$this->product_code."'";} ?> />&nbsp;&nbsp;
        <input type="submit" class="info_search_botton" value="Search" />
    </form>
</div>
<div align="center">
    <table class="hide" border="0" cellpadding="0" cellspacing="1">
                    <table class="width100" cellspacing="1">
                        <tbody>
                            <tr>
                                <td class="form-title">Product Code</td>
                                <td class="form-title">Product Title</td>
                                <td class="form-title">Category 1</td>
                                <td class="form-title">Category 2</td>
                                <td class="form-title">RRP</td>
                                <td class="form-title">Sell</td>
                                <td class="form-title">Cost<p style="margin:0">(NO GST)</p></td>
                                <td class="form-title">Stock</td>
                                <td class="form-title">Supplier Sku</td>
                                <td class="form-title">Crazysales Price<p style="margin:0">(Include GST)</p></td>
                                <td class="form-title">Status</td>
                                <td class="form-title">Action</td>
                            </tr>
                            <?php if($this->list):
                                    $n = 1;
                                    foreach($this->list as $key => $list):
                            ?>
                            <tr class="row-<?php if(1==$n){echo $n;$n+=1;}else{echo $n;$n-=1;}?> productinfo"  product-id='<?=$list['product_id']?>'>
                                <td class="center product_code" data='product_code_<?=$list['product_id']?>' data-name='product_code'><span class="small" id='product_code_<?=$list['product_id']?>' value='<?=$list['product_code']?>'><?=$list['product_code']?></span></td>
                                <td class="center product_title" data='product_title_<?=$list['product_id']?>' data-name='product_title'><span class="small" id='product_title_<?=$list['product_id']?>' value='<?=$list['product_title']?>'><?=$list['product_title']?></span></td>
                                <td class="center category_1" data='category_1_<?=$list['product_id']?>' data-name='category_1'><span class="small" id='category_1_<?=$list['product_id']?>' value='<?=$list['category_1']?>'><?=$list['category_1']?></span></td>
                                <td class="center category_2" data='category_2_<?=$list['product_id']?>' data-name='category_2'><span class="small" id='category_2_<?=$list['product_id']?>' value='<?=$list['category_2']?>'><?=$list['category_2']?></span></td>
                                <td class="center rrp" data='rrp_<?=$list['product_id']?>' data-name='rrp'><span class="small" id='rrp_<?=$list['product_id']?>' value='<?=$list['rrp']?>'><?=$list['rrp']?></span></td>
                                <td class="center sell" data='sell_<?=$list['product_id']?>' data-name='sell'><span class="small" id='sell_<?=$list['product_id']?>' value='<?=$list['sell']?>'><?=$list['sell']?></span></td>
                                <td class="center cost" data='cost_<?=$list['product_id']?>' data-name='cost'><span class="small" id='cost_<?=$list['product_id']?>' value='<?=$list['cost']?>'><?=$list['cost']?></span></td>
                                <td class="center stock" data='stock_<?=$list['product_id']?>' data-name='stock'><span class="small" id='stock_<?=$list['product_id']?>' value='<?=$list['stock']?>'><?=$list['stock']?></span></td>
                                <td class="center cc_supplier_sku" data='cc_supplier_sku_<?=$list['product_id']?>' data-name='cc_supplier_sku'><span class="small" id='cc_supplier_sku_<?=$list['product_id']?>' value='<?=$list['cc_supplier_sku']?>'><?=$list['cc_supplier_sku']?></span></td>
                                <td class="center cc_price" data='cc_price_<?=$list['product_id']?>' data-name='cc_price'><span class="small" id='cc_price_<?=$list['product_id']?>' value='<?=$list['cc_price']?>'><?=$list['cc_price']?></span></td>
                                <td class="center"><span class="small">
                                        <select name="status" id="status"  product-id="<?=$list['product_id']?>" onchange="javascript:update_status(<?=$list['product_id']?>,this);">
                                            <option value="-1" >Please Select Status</option>
                                            <option value="-1" >Reject</option>
                                            <option value="1"  >Default</option>
                                            <option value="2"  >Upload txt only</option>
                                            <option value="3"  >Upload image only</option>
                                            <option value="4"  >Upload txt and images</option>
                                            <option value="5"  >Static Stock</option>
                                        </select>
                                        <span id="order_status_<?=$list['product_id']?>">
								<?php
                                    switch ($list['status'])
                                    {
                                        case '-1':
                                            echo "<font color='red'>Reject.</font>";
                                            break;
                                        case 1:
                                            echo "<font color='green'>Default</font>";
                                            break;
                                        case 2:
                                            echo "<font color='red'>Upload txt only</font>";
                                            break;
                                        case 3:
                                                echo "<font color='red'>Upload image only</font>";
		                                break;
                                        case 4:
                                                echo "<font color='red'>Upload txt and images</font>";
		                                break;
                                        case 5:
                                                echo "<font color='red'>Static Stock</font>";
		                                break;
                                    }
								?> 
                                        </span>
                                    </span></td>
                                <td class="center"><span class="small"><a href="/admin/admin-order-view/user_id/<?=$this->user_id?>/order_id/<?=$list['product_id']?>">View</a></span></td>
                            </tr>
                            <?php
                                    endforeach;
                                endif;
                            ?>
                        </tbody>
                    </table>
</div>
<div align="right"><?=$this->pagination?>&nbsp;&nbsp;</div>
</div>
<script language="javascript">
function update_status(_product_id, _order_status){
    var _html   =   '';
    $.ajax({
            url:"/ajax/update-dd-product-status",
            dataType:"json",
            type:"POST",
            data:{
                product_id: _product_id,
                status:$(_order_status).children('option:selected').val(),
            },
            beforeSend:function(){
                
            },
            success:function(req){
                var obj = jQuery.parseJSON(req);
                if(req != null){
                    if(req.result == '1' && req.product_id != null && req.product_status != null){
                        if(req.product_status){
                            switch(req.product_status){
                                case '-1':
                                    _html   =   "<font color='red'>Reject.</font>";
                                    break;
                                case '1':
                                    _html   =   "<font color='green'>Default</font>";
                                    break;
                                case '2':
                                    _html   =   "<font color='red'>Upload txt only</font>";
                                    break;
                                case '3':
                                    _html   =   "<font color='red'>Upload image only</font>";
                                    break;
                                case '4':
                                    _html   =   "<font color='red'>Upload txt and images</font>";
                                    break;
                                case '5':
                                    _html   =   "<font color='red'>Static Stock</font>";
                                    break;
                            }
                            $('#order_status_' + req.product_id).html("");
                            $('#order_status_' + req.product_id).html(_html);
                        }
                    }
                }
            }
    })
}
$('.productinfo td').click(function (){
    var _product_id     =   $(this).parent().attr('product-id');
    var obj             =   '#' + $(this).attr('data');
    var _data_name      =   $(this).attr('data-name');
    var _old_comment    =   $(obj).attr('value');
    $(obj).html("");
    var _text = $("<input type=\"text\" >").css({ "width": $(this).width(), "border": "1px lightgrey solid" }).attr('value',_old_comment.replace(/\s*/,"")).appendTo($(obj));
    _text.focusEnd();
    //_text.attr('value',_old_comment.replace(/\s*/,""));
    _text.blur(function (){
        var _comments   =   _text.attr('value');
        if(_comments == ''){
            alert('Comments is Required.');
            return false;
        }
        $.ajax({
            url: "/ajax/update-dd-product-data",
            dataType:"json",
            type:"POST",
            data:{product_id:_product_id,data_value:_comments,data_name:_data_name}, 
            success:function(req){
                var _new_comments;
                if(req.result == '1'){
                    _new_comments   =   req.product_data[_data_name];
                }else{
                    _new_comments   =   _old_comment;
                }
                $(obj).html("");
                $(obj).html(_new_comments);
                $(obj).attr('value',_new_comments);
            },
            error: function(msg) {
                alert(msg);
                $(obj).html("");
                $(obj).html(_comments);
            }
            
        })
    })
})
$.fn.setCursorPosition = function(position){
    if(this.lengh == 0) return this;
    return $(this).setSelection(position, position);
}

$.fn.setSelection = function(selectionStart, selectionEnd) {
    if(this.lengh == 0) return this;
    input = this[0];

    if (input.createTextRange) {
        var range = input.createTextRange();
        range.collapse(true);
        range.moveEnd('character', selectionEnd);
        range.moveStart('character', selectionStart);
        range.select();
    } else if (input.setSelectionRange) {
        input.focus();
        input.setSelectionRange(selectionStart, selectionEnd);
    }

    return this;
}

$.fn.focusEnd = function(){
    this.setCursorPosition(this.val().length);
}
</script>
