<br />
<div align="center">
    <table class="hide" border="0" cellpadding="0" cellspacing="1">
        <tbody>
            <tr>
                <td valign="top" width="100%">
                    <table class="width100" cellspacing="1">
                        <tbody>
                            <tr>
                                <td class="form-title"><?=$this->help_info['h_subject']?></td>
                            </tr>
                            <tr class="row-2">
                                <td class="left"><span class="small"><?=$this->help_info['h_contents']?></span></td>
                            </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
        </tbody>
    </table>
</div>