
<script>
    function help_add()
    {
        window.location.href = "/admin/help-add";
    }
</script>
<script language="javascript"><!--
function senfe(o,a,b,c,d){
 var t=document.getElementById(o).getElementsByTagName("tr");
 for(var i=0;i<t.length;i++){
  t[i].style.backgroundColor=(t[i].sectionRowIndex%2==0)?a:b;
  t[i].onclick=function(){
   if(this.x!="1"){
    this.x="1";//本来打算直接用背景色判断，FF获取到的背景是RGB值，不好判断
    this.style.backgroundColor=d;
   }else{
    this.x="0";
    this.style.backgroundColor=(this.sectionRowIndex%2==0)?a:b;
   }
  }
  t[i].onmouseover=function(){
   if(this.x!="1")this.style.backgroundColor=c;
  }
  t[i].onmouseout=function(){
   if(this.x!="1")this.style.backgroundColor=(this.sectionRowIndex%2==0)?a:b;
  }
 }
}
--></script>
<div align="center" class="info_tablebox">
<form name="form1" id="form1" method="post" />
	<table class="hide" border="0" cellpadding="0" cellspacing="1">
					<table class="width100" cellspacing="1" id="senfe">
						<tbody>
							<tr>
								<td class="form-title">Time</td>
								<td class="form-title">Category</td>
								<td class="form-title">Subject</td>
								<td class="form-title">Status</td>
								<td class="form-title">Action</td>
							</tr>
							<?php if($this->list):
									$n = 1;
									foreach($this->list as $list):
							?>
							<tr class="row-<?php if(1==$n){echo $n;$n+=1;}else{echo $n;$n-=1;}?>">
								<td class="center"><span class="small"><?=date('H:i:s, d M Y ',strtotime($list['issue_time']))?></span></td>
								<td class="center"><span class="small"><?=$this->category_array[$list['category']]?></span></td>
								<td class="center"><span class="small"><?=$list['h_subject']?></span></td>
								<td class="center"><span class="small"><a  style=" color:#086d9d "href="/admin/update-help-status/helpdesk_id/<?=$list['helpdesk_id']?>" title="Update Topic Status"><?=$list['h_status']?"<font >Active</font>":"<font color='red'>Deleted</font>"?></a></span></td>
								<td class="center"><span class="small"><a href="/admin/help-preview/helpdesk_id/<?=$list['helpdesk_id']?>">Preview</a>&nbsp;&nbsp;&nbsp;<a href="/admin/help-edit/helpdesk_id/<?=$list['helpdesk_id']?>">Edit</a></span></td>
							</tr>
							<?php
									endforeach;
								endif;
							?>
						</tbody>
					</table>

            <div align="center"class="info_bottonp" >&nbsp;&nbsp;<input class="special_button_style_green" type="button" onclick="help_add();" value="Add Topic"></div>
</form>
</div>
<script language="javascript"><!--
//senfe("表格名称","奇数行背景","偶数行背景","鼠标经过背景","点击后背景");
senfe("senfe","#f8f8f8","#e8f5f9","#ccc","");

--></script>