<br />
<div align="center" class="info_tablebox">
    <table class="hide" border="0" cellpadding="0" cellspacing="1">

                    <table class="width100" cellspacing="1">
                        <tbody>
                            <tr>
                                <td class="form-title"><?=$this->help_info['h_subject']?></td>
                            </tr>
                            <tr class="row-2">
                                <td class="left"><span class="small"><?=$this->help_info['h_contents']?></span></td>
                            </tr>
                        </tbody>
                    </table>
    </table>
</div>