<script>
    function help_add()
    {
        window.location.href = "/admin/help-add";
    }
</script>
<div align="center">
<form name="form1" id="form1" method="post" />
	<table class="hide" border="0" cellpadding="0" cellspacing="1">
		<tbody>
			<tr>
				<td valign="top" width="100%">
					<table class="width100" cellspacing="1">
						<tbody>
							<tr>
								<td class="form-title">Time</td>
								<td class="form-title">Category</td>
								<td class="form-title">Subject</td>
								<td class="form-title">Status</td>
								<td class="form-title">Action</td>
							</tr>
							<?php if($this->list):
									$n = 1;
									foreach($this->list as $list):
							?>
							<tr class="row-<?php if(1==$n){echo $n;$n+=1;}else{echo $n;$n-=1;}?>">
								<td class="center"><span class="small"><?=$list['issue_time']?></span></td>
								<td class="center"><span class="small"><?=$this->category_array[$list['category']]?></span></td>
								<td class="center"><span class="small"><?=$list['h_subject']?></span></td>
								<td class="center"><span class="small"><a href="/admin/update-help-status/helpdesk_id/<?=$list['helpdesk_id']?>" title="Update Topic Status"><?=$list['h_status']?"<font color='green'>Active</font>":"<font color='red'>Deleted</font>"?></a></span></td>
								<td class="center"><span class="small"><a href="/admin/help-edit/helpdesk_id/<?=$list['helpdesk_id']?>">Edit</a></span></td>
							</tr>
							<?php
									endforeach;
								endif;
							?>
						</tbody>
					</table>
				</td>
			</tr>
		</tbody>
	</table>
</form>
</div>

&nbsp;&nbsp;<input class="special_button_style_green" type="button" onclick="help_add();" value="Add Topic">