<script language="javascript">
$(function ()
{
    $("#refresh_order").click(function (){
        $.ajax({
                    url:"/admin/admin-refresh-pending-orders",
                    dataType:"json",
                    type:"POST",
                    
                    beforeSend:function(){
                        $("#refresh_order").attr('disabled','disabled');
                        $("#refresh_order").attr('value','Refreshing');
                    },
                    success:function(req){
						
						var obj = $.toJSON(req);

						if(obj.recent_orders_list)
						{
							$('#pending_orders tbody').html('');

							for(var i = 0; i < obj.recent_orders_list.length; i++)
							{
								a = obj.recent_orders_list[i];
								var data = '';

								if(i%2 == 0)
								{
									data = '<tr class="row-1">';
								}
								else
								{
									data = '<tr class="row-2">';
								}

								data += '<td class="center"><span class="small">'+date('H:i:s, d M Y ', strtotime(a.issue_time))+'</span></td>';
								data += '<td class="center"><span class="small">'+a.main_db_order_id+'</span></td>';
								date += '<td class="center"><span class="small">'+a.merchant_ref+'</span></td>';
								date += '<td class="center"><span class="small">'+a.supplier_sku+'</span></td>';
								date += '<td class="center"><span class="small">'+a.merchant_sku+'</span></td>';
								date += '<td class="center"><span class="small">'+a.item_amount+'</span></td>';
								date += '<td class="center" onmouseover="show_status(\'recent_'+i+'\');" onmouseout="hide_status(\'recent_'+i+'\');"><span class="small">';

                            	switch (a.item_status)
		                        {
		                            case 0:
		                                date += "<font color='red'>Pending</font>";
		                                break;
		                            case 1:
		                                date += "<font color='green'>Approved</font>";
		                                break;
		                            case 2:
		                                date += "<font color='red' style='TEXT-DECORATION: underline'>Rejected</font><div id='status_recent_"+i+"' class='api_response' style='display: none;'>"+a.api_response+"</div>";
		                                break;
		                        }
								data += '</span></td>';
                    			date += '<td class="center"><span class="small"><a href="/admin/admin-order-view/user_id/'+a.user_id+'/order_id/'+a.purchase_order_id+'">View</a></span></td>';
                				data += '</tr>';

								$('#pending_orders tbody').append(data);

								if(obj.refresh_num)
								{
									alert(obj.refresh_num+' was affected');
								}
							}
						} 
		                //        location.reload();
						alert(req);
                    },
					error: function(msg) {
						alert(msg);
					}
                })
    });
});

function show_status(index)
{
	if($("#status_"+index))
	{
		$("#status_"+index).show();
	}
}

function hide_status(index)
{
	if($("#status_"+index))
	{
		$("#status_"+index).hide();
	}
}
</script>
<br />
&nbsp;Welcome back, Admin.
<div class="info_tablebox">
    <h2>Scheduled Summary</h2>
    <div>
        <p><span>Product Info Refresh Time: </span><span <?php if($this->product_info_table_refresh_flag){?>class="red"<?php }?>><?=date('H:i:s, d M Y ',strtotime($this->product_info_table_refresh_time))?></span></p>
        <p><span>Pending Order Refresh Time: </span><span <?php if($this->pending_order_refresh_flag){?>class="red"<?php }?>><?=date('H:i:s, d M Y ',strtotime($this->pending_order_refresh_time))?></span></p>
        <p><span>Product Categories Refresh Time: </span><span <?php if($this->product_categories_table_refresh_flag){?>class="red"<?php }?>><?=date('H:i:s, d M Y ',strtotime($this->product_categories_table_refresh_time))?></span></p>
        <p><span>Merchant Feed Refresh Time: </span><span <?php if($this->merchant_feed_refresh_flag){?>class="red"<?php }?>><?=date('H:i:s, d M Y ',strtotime($this->merchant_feed_refresh_time))?></span></p>
    </div>
    
    <h2>Recent 10 Orders</h2>
    <div align="center">
        <table class="width100" cellspacing="1">
            <tbody>
                <tr> 
                    <td class="form-title">Time</td>
                    <td class="form-title">Order ID</td>
                    <td class="form-title">Merchant Ref</td>
                    <td class="form-title">Supplier SKU</td>
                    <td class="form-title">Merchant SKU</td>
                    <td class="form-title">Order Amount<p style="margin:0">(Include GST and postage)</p></td>
                    <td class="form-title">Status</td>
                    <td class="form-title">Action</td>
                </tr>
                <?php if($this->recent_orders_list):
                        $n = 1;
                        foreach($this->recent_orders_list as $key => $recent_order):
                ?>
                <tr class="row-<?php if(1==$n){echo $n;$n+=1;}else{echo $n;$n-=1;}?>">
                    <td class="center"><span class="small"><?=date('H:i:s, d M Y ',strtotime($recent_order['issue_time']))?></span></td>
                    <td class="center"><span class="small"><?=$recent_order['main_db_order_id']?></span></td>
                    <td class="center"><span class="small"><?=$recent_order['merchant_ref']?></span></td>
                    <td class="center"><span class="small"><?=$recent_order['supplier_sku']?></span></td>
                    <td class="center"><span class="small"><?=$recent_order['merchant_sku']?></span></td>
                    <td class="center"><span class="small"><?=$recent_order['item_amount']?></span></td>
                    <td class="center" onmouseover="show_status('<?php echo 'recent_'.$key; ?>');" onmouseout="hide_status('<?php echo 'recent_'.$key; ?>');"><span class="small">
                            <?php 
                            switch ($recent_order['item_status'])
                            {
                                case 0:
                                    echo "<font color='red'>Pending</font>";
                                    break;
                                case 1:
                                    echo "<font color='green'>Approved</font>";
                                    break;
                                case 2:
                                    echo "<font color='red' style='TEXT-DECORATION: underline'>Rejected</font><div id='status_recent_".$key."' class='api_response' style='display: none;'>".$recent_order['api_response']."</div>";
                                    break;
                            }
                            ?>

                        </span></td>
                    <td class="center"><span class="small"><a href="/admin/admin-order-view/user_id/<?=$recent_order['user_id']?>/order_id/<?=$recent_order['purchase_order_id']?>">View</a></span></td>
                </tr>
                <?php
                        endforeach;
                    endif;
                ?>
            </tbody>
        </table>
    </div>
    
    <?php //if($this->list):?>
    <h2>Pending Orders</h2>
    <div align="center">
        <table id="pending_orders" class="width100" cellspacing="1">
			<thead>
                <th>
                    <td class="form-title">Time</td>
                    <td class="form-title">Order ID</td>
                    <td class="form-title">Merchant Ref</td>
                    <td class="form-title">Supplier SKU</td>
                    <td class="form-title">Merchant SKU</td>
                    <td class="form-title">Order Amount<p style="margin:0">(Include GST and postage)</p></td>
                    <td class="form-title">Status</td>
                    <td class="form-title">Action</td>
                </th>
			<thead>
            <tbody>
                <?php if($this->list):
                        $n = 1;
                        foreach($this->list as $key => $list):
                ?>
                <tr class="row-<?php if(1==$n){echo $n;$n+=1;}else{echo $n;$n-=1;}?>">
                    <td class="center"><span class="small"><?=date('H:i:s, d M Y ',strtotime($list['issue_time']))?></span></td>
                    <td class="center"><span class="small"><?=$list['main_db_order_id']?></span></td>
                    <td class="center"><span class="small"><?=$list['merchant_ref']?></span></td>
                    <td class="center"><span class="small"><?=$list['supplier_sku']?></span></td>
                    <td class="center"><span class="small"><?=$list['merchant_sku']?></span></td>
                    <td class="center"><span class="small"><?=$list['item_amount']?></span></td>
                    <td class="center" onmouseover="show_status('<?php echo 'pending_'.$key; ?>');" onmouseout="hide_status('<?php echo 'pending_'.$key; ?>');"><span class="small">
                            <?php 
                            switch ($list['item_status'])
                            {
                                case 0:
                                    echo "<font color='red'>Pending</font>";
                                    break;
                                case 1:
                                    echo "<font color='green'>Approved</font>";
                                    break;
                                case 2:
                                    echo "<font color='red' style='TEXT-DECORATION: underline'>Rejected</font><div id='status_pending_".$key."' class='api_response' style='display: none;'>".$list['api_response']."</div>";
                                    break;
                            }
                            ?>

                        </span></td>
                    <td class="center"><span class="small"><a href="/admin/admin-order-view/user_id/<?=$list['user_id']?>/order_id/<?=$list['purchase_order_id']?>">View</a></span></td>
                </tr>
                <?php
                        endforeach;
                    endif;
                ?>
            </tbody>
        </table>
        <div class="info_bottonp" align="center">
            <input class="special_button_style_green" type="button" value="Refresh Order" id="refresh_order">
            <br>
        </div>
    </div>
    <?php //endif;?>
</div>
