
<div align="center" class="info_tablebox">
 
<div align="center class="row-1"><H2>Adjust balance for merchant: <?=$this->user['company']?></H2></div>

    <form action="/admin/merchant-recharge-preview" method="POST">
        <table class="hide" border="0" cellpadding="0" cellspacing="1">
                        <table class="width100" cellspacing="1">
                            <tbody>
                                <tr class="row-1">
                                    <td class="right" width="50%">Current Balance</td>
                                    <td class="left" width="50%"><?=$this->user['balance']?></td>
                                </tr>
                                <tr class="row-2">
                                    <td class="right">Action</td>
                                    <td class="left">
                                        <select name="adj" id="adj">
                                            <option value="1">Recharge</option>
                                            <option value="2">Deduct</option>
                                        </select>
                                    </td>
                                </tr>
                                <tr class="row-1">
                                    <td class="right">Adjustment Value</td>
                                    <td class="left"><input type="text" size="5" name="val" id="val" /></td>
                                </tr>
                                <tr >
                                    <td class="right"></td>
                                    <td class="left info_botton2" ><input type="hidden" name="user_id" id="user_id" value="<?=$this->user['user_id']?>" /><input  class="special_button_style_green" type="submit" value="Continue" /></td>
                                </tr>
                            </tbody>
                        </table>
        </table>
    </form>
</div>