<link rel="stylesheet" href="/styles/zTreeStyle/zTreeStyle.css" type="text/css">
<script type="text/javascript" src="/scripts/jquery.ztree.core-3.5.js"></script>
<script type="text/javascript" src="/scripts/jquery.ztree.excheck-3.5.js"></script>
	<SCRIPT type="text/javascript">
		<!--
		function zTreeOnCheck(event, treeId, treeNode) {
                    
                    $.ajax({
                        url:"/ajax/tree-affect-of-category",
                        type:"POST",
                        data:{"TreeID":treeNode.id,"ParentID":treeNode.pId, "Checked":treeNode.checked, "UserID":<?=$this->user_info['user_id']?>},
                        datatype:"json",
                        success:function(data)
                        {
                            //happy
                        }
                    });
                };
        
                var setting = {
			check: {
				enable: true
			},
			data: {
				simpleData: {
					enable: true
				}
			},
                        callback: {
                            onCheck: zTreeOnCheck
                        }
		};

		var zNodes =[
                    <?php foreach($this->product_categories as $product_categories):?>
                            { id:<?=$product_categories['category_id']?>, pId:<?=$product_categories['parent_id']?>, name:"<?=$product_categories['category_name']?>", checked:<?=$product_categories['checked']?>, open:<?=$product_categories['open']?>},
                    <?php endforeach;?>
		];

		var code;

		function setCheck() {
			var zTree = $.fn.zTree.getZTreeObj("categoryTree"),
			py = $("#py").attr("checked")? "p":"",
			sy = $("#sy").attr("checked")? "s":"",
			pn = $("#pn").attr("checked")? "p":"",
			sn = $("#sn").attr("checked")? "s":"",
			type = { "Y":"ps", "N":"ps"};
			zTree.setting.check.chkboxType = type;
			showCode('setting.check.chkboxType = { "Y" : "' + type.Y + '", "N" : "' + type.N + '" };');
		}
		function showCode(str) {
			if (!code) code = $("#code");
			code.empty();
			code.append("<li>"+str+"</li>");
		}

		$(document).ready(function(){
			$.fn.zTree.init($("#categoryTree"), setting, zNodes);
			setCheck();
			$("#py").bind("change", setCheck);
			$("#sy").bind("change", setCheck);
			$("#pn").bind("change", setCheck);
			$("#sn").bind("change", setCheck);
		});
		//-->
	</SCRIPT>
<script>
$(function() {
$( "#sortable" ).sortable();
});
</script>
<script language="JavaScript">
		$(document).ready(function() {
			$(".selectall").click(function() {
				var checked_status = this.checked;
				var checkbox_name = this.name;
				$("input[id=" + checkbox_name + "]").each(function() {
					this.checked = checked_status;
				});
			});
		});
</script>
<script>
jQuery(function($){
  $('#publish').click(function(){
        $.ajax({
            url:"/ajax/refresh-feed",
            type:"POST",
            data:{"UserId":<?=$this->user_info['user_id']?>},
            datatype:"json",
            success:function(data)
            {
                alert(data);
            }
        });
  });
});
</script>
<br />
<?php if($this->notice):?>
<?php echo $this->notice;?><br /><br />
<?php endif;?>
<div align="center" class="info_tablebox" >
<form action="/admin/merchant-feed-generation-confirm/user_id/<?=$this->user_info['user_id']?>" method="post">
	<table class="width100" cellspacing="1">
		<tbody>
			<tr>
				<td class="form-title" colspan="4">Generate Feed for <?=$this->user_info['company']?>&nbsp;&nbsp;&nbsp;<a href="/admin/help-preview/helpdesk_id/7" target="_blank"><img src="/images/help2.png" title="Feed Generation Document" border="0" /></a></td>
			</tr>		
			<tr class="row-1">
				<td class="category">URL</td>
				<td colspan="3"><a href="<?=$this->feed_path?>" target="_blank"><?=$this->feed_path?></a></td>
			</tr>			
			<tr class="row-2">
				<td class="category">Feed Name</td>
				<td colspan="3"><input type="text" name="feed_name" id="feed_name" value="<?=($this->users_feed['feed_name']?$this->users_feed['feed_name']:$this->initial_feed_name)?>" /></td>
			</tr>
			<tr class="row-1">
				<td class="category">Extension</td>
				<td colspan="3">
                                    <input type="radio" name="feed_extension" id="feed_extension" value="1" <?php if(1==$this->users_feed['feed_extension'] || !$this->users_feed['users_feed_id']):?>checked="checked"<?php endif;?> />CSV&nbsp;&nbsp;
                                    <input type="radio" name="feed_extension" id="feed_extension" value="2" <?php if(2==$this->users_feed['feed_extension']):?>checked="checked"<?php endif;?> />TXT&nbsp;&nbsp;
                                    <input type="radio" name="feed_extension" id="feed_extension" value="3" <?php if(3==$this->users_feed['feed_extension']):?>checked="checked"<?php endif;?> />XML
                                </td>
			</tr>				
			<tr class="row-2">
				<td class="category">Delimeter</td>
				<td colspan="3">
                                    <input type="radio" name="feed_delimeter" id="feed_delimeter" value="1" <?php if(1==$this->users_feed['feed_delimeter']):?>checked="checked"<?php endif;?> />Tab&nbsp;&nbsp;
                                    <input type="radio" name="feed_delimeter" id="feed_delimeter" value="2" <?php if(2==$this->users_feed['feed_delimeter']):?>checked="checked"<?php endif;?> />Semicolon(;)&nbsp;&nbsp;
                                    <input type="radio" name="feed_delimeter" id="feed_delimeter" value="3" <?php if(3==$this->users_feed['feed_delimeter'] || !$this->users_feed['users_feed_id']):?>checked="checked"<?php endif;?> />Comma(,)&nbsp;&nbsp;
                                    <input type="radio" name="feed_delimeter" id="feed_delimeter" value="4" <?php if(4==$this->users_feed['feed_delimeter']):?>checked="checked"<?php endif;?> />Space&nbsp;&nbsp;
                                    <input type="radio" name="feed_delimeter" id="feed_delimeter" value="5" <?php if(5==$this->users_feed['feed_delimeter']):?>checked="checked"<?php endif;?> /> <input type="text" name="special_delimeter" id="special_delimeter" size="1" value="<?=$this->users_feed['special_delimeter']?>" />
                                </td>
			</tr>	
			<tr class="row-1">
				<td class="category">Qualifier</td>
				<td colspan="3">
                                    <input type="radio" name="feed_qualifier" id="feed_qualifier" value="1" <?php if(1==$this->users_feed['feed_qualifier'] || !$this->users_feed['users_feed_id']):?>checked="checked"<?php endif;?> />None&nbsp;&nbsp;
                                    <input type="radio" name="feed_qualifier" id="feed_qualifier" value="2" <?php if(2==$this->users_feed['feed_qualifier']):?>checked="checked"<?php endif;?> />( " )&nbsp;&nbsp;
                                    <input type="radio" name="feed_qualifier" id="feed_qualifier" value="3" <?php if(3==$this->users_feed['feed_qualifier']):?>checked="checked"<?php endif;?> />( ' )
                                </td>
			</tr>		
			<tr class="row-2">
				<td class="category">Column Definition</td>
				<td colspan="3">
                                    <div class="tsale">
                                        <div class="ulwrap">
                                            <div>
                                                <ul class="shuzi">
                                                    <li class="first">Sequence</li>
                                                </ul>
                                                <ul class="contentlist">
                                                    <li class="first"><input type="checkbox" class="selectall" name="ckd" /> / Column Alias / Value / Value Adjustment / Change Sequence *</li>
                                                </ul>
                                            </div>
                                            <ul class="shuzi">
                                                <?php for($n=1;$n<=$this->get_column_info[1];$n++): ?>
                                                    <li><?=$n?></li>
                                                <?php endfor;?>
                                            </ul>
                                            <ul id="sortable" class="contentlist">
                                                <?php foreach($this->get_column_info[2] as $column_info):?>
                                                    <li><input type="checkbox" name="ckd[<?=$column_info['feed_dictionary_id']?>]" id="ckd" <?php if(($this->users_feed['users_feed_id'] && $column_info['checked']) || (!$this->users_feed['users_feed_id'] && "[Custom]" != $column_info['column_alias'])):?>checked="checked"<?php endif;?> /><input type="text" name="column_alias[<?=$column_info['feed_dictionary_id']?>]" value="<?=$column_info['column_alias']?>" /><input type="text" name="column_value[<?=$column_info['feed_dictionary_id']?>]" value="<?=$column_info['column_value']?>" /><input type="text" name="column_value_adjustment[<?=$column_info['feed_dictionary_id']?>]" value="<?=$column_info['column_value_adjustment']?>" />&nbsp;&nbsp;&nbsp;<span class="ui-icon ui-icon-arrowthick-2-n-s"></span></li>
                                                <?php endforeach;?>
                                            </ul>
                                            <div class="clear"></div>
                                        </div>
                                    </div>
                                </td>
			</tr>
			<tr class="row-1">
				<td class="category">Category</td>
				<td colspan="3">
                                    <div>
                                        <ul id="categoryTree" class="ztree"></ul>
                                    </div>
                                </td>
			</tr>				
			<tr class="row-2">
				<td class="category">SKUs included</td>
                                <td colspan="3"><textarea name="sku_included" id="sku_included" cols="100" rows="3"><?=$this->users_feed['sku_included']?></textarea></td>
			</tr>
			<tr class="row-1">
				<td class="category">SKUs excluded</td>
				<td colspan="3"><textarea name="sku_excluded" id="sku_excluded" cols="100" rows="3"><?=$this->users_feed['sku_excluded']?></textarea></td>
			</tr>
                        <tr class="row-2">
				<td class="category">Shipping Courier</td>
                                <td colspan="3">
                                    <input type="checkbox" name="sc_class[]" id="shipping_courier" value="3" <?php if(3==$this->users_feed['sc_class_array']['3']):?>checked="checked"<?php endif;?> /><label>eParcel</label>
                                    <input type="checkbox" name="sc_class[]" id="shipping_courier" value="5" <?php if(5==$this->users_feed['sc_class_array']['5']):?>checked="checked"<?php endif;?> /><label>Regular Mail</label>
                                    <input type="checkbox" name="sc_class[]" id="shipping_courier" value="7" <?php if(7==$this->users_feed['sc_class_array']['7']):?>checked="checked"<?php endif;?> /><label>Toll IPEC</label>
                                    <input type="checkbox" name="sc_class[]" id="shipping_courier" value="1" <?php if(1==$this->users_feed['sc_class_array']['1']):?>checked="checked"<?php endif;?> /><label>TIG Big</label> 
                                </td>
			</tr>
			<tr class="row-1">
				<td class="category">Supplier Type</td>
				<td colspan="3">
                                    <input type="checkbox" name="supplier_type[]" id="supplier_type" value="AU" <?php if('AU'==$this->users_feed['supplier_type_array']['AU']):?>checked="checked"<?php endif;?> /><label>AU</label>
                                    <input type="checkbox" name="supplier_type[]" id="supplier_type" value="CN" <?php if('CN'==$this->users_feed['supplier_type_array']['CN']):?>checked="checked"<?php endif;?> /><label>CN</label>
                                    <input type="checkbox" name="supplier_type[]" id="supplier_type" value="HK" <?php if('HK'==$this->users_feed['supplier_type_array']['HK']):?>checked="checked"<?php endif;?> /><label>HK</label>
                                </td>
			</tr>
			<tr class="row-2">
				<td class="category">Stock</td>
                                <td colspan="3">
                                    <input type="radio" name="stock" id="stock" value="1" <?php if(1==$this->users_feed['stock'] || !$this->users_feed['users_feed_id']):?>checked="checked"<?php endif;?> />All&nbsp;&nbsp;
                                    <input type="radio" name="stock" id="stock" value="2" <?php if(2==$this->users_feed['stock']):?>checked="checked"<?php endif;?> />In Stock&nbsp;&nbsp;
                                    <input type="radio" name="stock" id="stock" value="3" <?php if(3==$this->users_feed['stock']):?>checked="checked"<?php endif;?> />Out of Stock
                                </td>
			</tr>
			<tr class="row-1">
				<td class="category">Discount Protection</td>
                                <td colspan="3">
                                    <input type="radio" name="cost_protection" id="cost_protection" value="1" <?php if(1==$this->users_feed['cost_protection']):?>checked="checked"<?php endif;?> />ON
                                    <input type="radio" name="cost_protection" id="cost_protection" value="0" <?php if(!$this->users_feed['cost_protection'] || !$this->users_feed['users_feed_id']):?>checked="checked"<?php endif;?> />OFF
                                </td>
			</tr>	
			<tr >
                                <td ></td>
				<td colspan="3" class="info_botton2">
                                    <input type="submit" class="special_button_style_green" value="Save" />&nbsp;&nbsp;&nbsp;<input  class="special_button_style_green"type="button" id="publish" value="Publish" />
                                </td>
			</tr>
		</tbody>
	</table>
    
    
</form>
</div>
