
<div align="center" class="info_tablebox">
    <div align="center"><H2><font color="red">Please confirm your action.</font></H2></div>
    <form action="/admin/merchant-recharge-preview/update/1" method="POST">
        <table class="hide" border="0" cellpadding="0" cellspacing="1">
                        <table class="width100" cellspacing="1">
                            <tbody>
                                <tr class="row-1">
                                    <td class="right" width="50%">Current Balance</td>
                                    <td class="left" width="50%"><?=$this->current_balance?></td>
                                </tr>
                                <tr class="row-2">
                                    <td class="right" width="50%">Action</td>
                                    <td class="left" width="50%"><?=$this->action_type?><?=$this->adjust_value?></td>
                                </tr>
                                <tr class="row-1">
                                    <td class="right" width="50%">New Balance</td>
                                    <td class="left" width="50%"><?=$this->new_balance?></td>
                                </tr>
                                <tr class="">
                                    <td class="center info_botton2" colspan="2">
                                        <input class="special_button_style_green" type="hidden" name="adj" id="adj" value="<?=$this->action_type?>" />
                                        <input class="special_button_style_green" type="hidden" name="val" id="val" value="<?=$this->adjust_value?>" />
                                        <input class="special_button_style_green" type="hidden" name="user_id" id="user_id" value="<?=$this->user['user_id']?>" />
                                        <input class="special_button_style_green" type="submit" value="Confirm Update" /></td>
                                </tr>
                            </tbody>
                        </table>
        </table>
    </form>
</div>