<script>
    function merchant_add()
    {
        window.location.href = "/admin/merchant-add";
    }
</script>
<script language="javascript"><!--
function senfe(o,a,b,c,d){
 var t=document.getElementById(o).getElementsByTagName("tr");
 for(var i=0;i<t.length;i++){
  t[i].style.backgroundColor=(t[i].sectionRowIndex%2==0)?a:b;
  t[i].onclick=function(){
   if(this.x!="1"){
    this.x="1";//本来打算直接用背景色判断，FF获取到的背景是RGB值，不好判断
    this.style.backgroundColor=d;
   }else{
    this.x="0";
    this.style.backgroundColor=(this.sectionRowIndex%2==0)?a:b;
   }
  }
  t[i].onmouseover=function(){
   if(this.x!="1")this.style.backgroundColor=c;
  }
  t[i].onmouseout=function(){
   if(this.x!="1")this.style.backgroundColor=(this.sectionRowIndex%2==0)?a:b;
  }
 }
}
--></script>
<div align="center" class="info_tablebox">
<form name="form1" id="form1" method="post" />
	<table class="hide" border="0" cellpadding="0" cellspacing="1">
					<table class="width100" cellspacing="1" id="senfe">
						<tbody>
							<tr>
								<td class="form-title">Company</td>
								<td class="form-title">Registration Date</td>
								<td class="form-title">Bpay Ref</td>
								<td class="form-title">Balance</td>
								<td class="form-title">Credit</td>
								<td class="form-title">Discount</td>
								<td class="form-title">Status</td>
								<td class="form-title">Actions</td>
								<td class="form-title">Reports</td>
							</tr>
							<?php if($this->list):
									$n = 1;
									foreach($this->list as $list):
							?>
							<tr class="row-<?php if(1==$n){echo $n;$n+=1;}else{echo $n;$n-=1;}?>">
								<td class="center"><span class="small"><?=$list['company']?></span></td>
								<td class="center"><span class="small"><?=$list['join_date']?></span></td>
								<td class="center"><span class="small"><?=$list['bpay_ref']?></span></td>
								<td class="center"><span class="small"><?=$list['balance']?></span></td>
								<td class="center"><span class="small"><?=$list['credit']?></span></td>
								<td class="center"><span class="small"><?=$list['discount']?>%</span></td>
								<td class="center"><span class="small " style="color:#086d9d" ><?=$list['user_status']?"<font >Active</font>":"<font >Inactive</font>"?></span></td>
								<td class="center"><span class="small"><a href="/admin/merchant-edit/user_id/<?=$list['user_id']?>">Edit</a> | <a href="/admin/merchant-recharge/user_id/<?=$list['user_id']?>">Recharge</a> | <a href="/admin/merchant-feed-generation/user_id/<?=$list['user_id']?>">Feed</a></span></td>
								<td class="center"><span class="small"><a href="/admin/admin-order-report/user_id/<?=$list['user_id']?>">Orders</a> | <a href="/admin/admin-financial-report/user_id/<?=$list['user_id']?>">Financial</a></span></td>
							</tr>
							<?php
									endforeach;
								endif;
							?>
						</tbody>
					</table>

	</table>
<div align="center"class="info_bottonp" >&nbsp;&nbsp;<input class="special_button_style_green" type="button" onclick="merchant_add();" value="Add Merchant"><br></div>
</form>
</div>
<script language="javascript"><!--
//senfe("表格名称","奇数行背景","偶数行背景","鼠标经过背景","点击后背景");
senfe("senfe","#f8f8f8","#e8f5f9","#ccc","");

--></script>
 
