<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
	<link rel="SHORTCUT ICON" href="/images/favicon.ico">
	<link type="text/css" href="/styles/ui-lightness/jquery-ui-1.8.4.custom.css" rel="stylesheet" />
        <script src="/scripts/jquery-1.8.1.js"></script>
        <script src="http://code.jquery.com/ui/1.10.1/jquery-ui.js"></script>
	<script src="/scripts/dojo.js" type="text/javascript"></script>
	<script src="/scripts/phpjs.js" type="text/javascript"></script>
	<link rel="stylesheet" type="text/css" href="/styles/<?=$this->system_css?>/default.css">
	<meta http-equiv="Content-type" content="text/html; charset=UTF-8">
	<title><?=$this->title?> - <?=$this->system_title?></title>
</head>
<body>
    <div class="info_topbg">
    <div class="info_logo"></div>
    <div class="info_toptxt">Hi <a style="color: #FFFFFF;" href="<?php if($this->user_type==2){?>/merchant/profile-edit<?php }else{ ?>/admin<?php } ?>"><?=$_SESSION["Zend_Auth"]["storage"]->email?></a></div>
    <div class="info_help">
        <ul>
            <?php if($this->user_type==2){?><li><a  href="/merchant/profile-edit">Profile</a></li><?php }?>
            <li><a  href="/login/logout">Logout</a></li>
        </ul>
    </div>
</div>
<div class="info_menu">
    <ul>
        <?=$this->top_menu?>
    </ul>
</div>   
<?php if(isset($this->navigation)): ?>
<div class="no-print info_place" cellspacing="0" >
    <ul>
	<li >&nbsp;&nbsp;<?=$this->navigation?></li>
        <li class="right nowrap"></li>
   </ul>
</div>
<?php endif; ?>
    
<?php echo $this->layout()->content; ?>
<table width="100%" border="0" cellpadding="0" cellspacing="0" class="info_footer">
	<tbody>
		<tr valign="top">
			<td><div align="right">
				<span class="timer"><?=$this->system_title?> <?=$this->system_version?><br />
				<address>Copyright © <?=date("Y");?> CrazySales</address>
				<span>
				</div>
			</td>
		</tr>
	</tbody>
</table>
</body>
</html>
