<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
	<link rel="SHORTCUT ICON" href="/images/favicon.ico">
	<link type="text/css" href="/styles/ui-lightness/jquery-ui-1.8.4.custom.css" rel="stylesheet" />
        <script src="/scripts/jquery-1.8.1.js"></script>
        <script src="http://code.jquery.com/ui/1.10.1/jquery-ui.js"></script>
	<script src="/scripts/dojo.js" type="text/javascript"></script>
	<link rel="stylesheet" type="text/css" href="/styles/default.css">
	<meta http-equiv="Content-type" content="text/html; charset=UTF-8">
	<title><?=$this->title?> - <?=$this->system_title?></title>
</head>
<body>
<div class="center"><span class="pagetitle"></span></div>
<table class="hide no-print">
	<tbody>
		<tr>
			<td class="login-info-left"><strong>Hi <?=$_SESSION["Zend_Auth"]["storage"]->email?></strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?=$this->top_menu?>&nbsp;&nbsp;&nbsp;&nbsp;| |&nbsp;&nbsp;&nbsp;&nbsp;<a href="/login/logout">Logout</a></td>
		</tr>
	</tbody>
</table>

<table class="width100 no-print" cellspacing="0">
	<tbody>
		<tr>
			<td class="menu">&nbsp;&nbsp;<?=$this->navigation?></td>
			<td class="menu right nowrap"></td>
		</tr>
	</tbody>
</table>

<?php echo $this->layout()->content; ?>

<br>
<table width="100%" border="0" cellpadding="0" cellspacing="0">
	<tbody>
		<tr valign="top">
			<td><div align="right">
				<span class="timer"><?=$this->system_title?> <?=$this->system_version?><br />
				<address>Copyright © <?=date("Y");?> CrazySales</address>
				<span>
				</div>
			</td>
		</tr>
	</tbody>
</table>
</body>
</html>
